// ============================================================
//  SymposiON — Site Data
//  grades, subjects, and game registry
// ============================================================

const GRADES = {
  'gym-a': {
    label: 'Γυμνάσιο · Α΄ τάξη', labelEn: 'Middle School · 7th Grade',
    title: 'Α΄ Γυμνασίου',        titleEn: '7th Grade',
    desc:  'Επίλεξε μάθημα.',     descEn:  'Choose a subject.',
    parent: 'Γυμνάσιο', parentEn: 'Middle School', parentKey: 'gymnasio',
    subjects: [
      { id: 'logotexnia',   icon: '📖', bg: 'linear-gradient(135deg,#1A2E10,#3B6D11)',
        title: 'Λογοτεχνία',         desc: 'Νεοελληνικά λογοτεχνικά κείμενα.', count: 4,
        en: { title: 'Literature',         desc: 'Modern Greek literary texts.' } },
      { id: 'nea-ellinika', icon: '✍️', bg: 'linear-gradient(135deg,#0D2A3A,#185FA5)',
        title: 'Νεοελληνική Γλώσσα', desc: 'Γραμματική, σύνταξη και κατανόηση.', count: 5,
        en: { title: 'Modern Greek Language', desc: 'Grammar, syntax and comprehension.' } },
      { id: 'archaia',      icon: '🏛️', bg: 'linear-gradient(135deg,#2A1A08,#7A4E1A)',
        title: 'Αρχαία Ελληνικά',    desc: 'Αρχαία κείμενα, μετάφραση και γραμματική.', count: 6,
        en: { title: 'Ancient Greek',        desc: 'Ancient texts, translation and grammar.' } },
      { id: 'odysseia',     icon: '🌊', bg: 'linear-gradient(135deg,#0D2A3A,#185FA5)',
        title: 'Οδύσσεια',           desc: 'Ραψωδίες, ήρωες και νόημα του έπους.', count: 5,
        en: { title: 'Odyssey',              desc: 'Rhapsodies, heroes and the meaning of the epic.' },
        extraGames: [
          { type: 'odyssey-trivia', icon: '🏺',
            label: 'Odyssey Trivia',
            desc: 'Ερωτήσεις πολλαπλής επιλογής — Σόλο, ΤΤΤ ή Tug of War.',
            en: { label: 'Odyssey Trivia', desc: 'Multiple choice questions — Solo, TTT or Tug of War.' } },
          { type: 'odyssey-journey', icon: '⚓',
            label: 'Οδύσσεια 3D — Περιπλάνηση',
            desc: '3D ταξίδι στη Μεσόγειο — 8 νησιά, 24 ερωτήσεις ραψωδιών.',
            en: { label: 'Odyssey 3D — The Journey', desc: '3D sail across the Mediterranean — 8 islands, 24 rhapsody questions.' } },
          { type: 'epic-puzzle', icon: '📋',
            label: 'Χρονολόγιο — Οδύσσεια', desc: 'Βάλε τα γεγονότα της Οδύσσειας στη σωστή χρονολογική σειρά — 5 γύροι.',
            en: { label: 'Chronicle — Odyssey', desc: 'Arrange Odyssey events in the correct chronological order — 5 rounds.' } },
          { type: 'myth-memory', icon: '🃏',
            label: 'Mythology Memory', desc: 'Βρες τα ζεύγη — ήρωες & επίθετα Οδύσσειας και Θεών.',
            en: { label: 'Mythology Memory', desc: 'Find the pairs — heroes & epithets from the Odyssey and Gods.' } },
          { type: 'rapid-fire', icon: '⚡',
            label: 'Καταιγισμός — Οδύσσεια', desc: 'Κράτα την καταιγίδα ζωντανή — άπειρες ερωτήσεις, εναλλασσόμενοι τύποι, επιλογή χρόνου!',
            en: { label: 'Kataigismos — Odyssey', desc: 'Keep the storm alive — infinite questions, alternating formats, you pick the clock!' } },
          { type: 'temple-run', icon: '🏛️',
            label: 'Temple Run — Αρχαία Αγορά',
            desc: 'Τρέξε στην Αρχαία Αγορά! Αποφύγε τους πλανόδιους πωλητές, μάζεψε δραχμές — τα ανθρωποφάγα βιβλία σε κυνηγούν!',
            en: { label: 'Temple Run — Ancient Agora', desc: 'Sprint through the Ancient Agora! Dodge roaming vendors, collect drachmas — cannibalistic textbooks are chasing you!' } },
          { type: 'labyrinth', icon: '🌀',
            label: 'Λαβύρινθος του Μινώταυρου',
            desc: 'Βρες τον Μινώταυρο! 7×7 πλέγμα με ομίχλη πολέμου — απάντα σωστά για να εξερευνήσεις το λαβύρινθο!',
            en: { label: 'Labyrinth of the Minotaur', desc: 'Find the Minotaur! 7×7 fog-of-war grid — answer correctly to explore the labyrinth!' } },
        ] },
      { id: 'istoria',      icon: '🗺️', bg: 'linear-gradient(135deg,#1A0D2A,#4A3890)',
        title: 'Ιστορία',            desc: 'Αρχαία ελληνική ιστορία.', count: 4,
        en: { title: 'History',              desc: 'Ancient Greek history.' },
        extraGames: [
          { type: 'history-game', icon: '🗺️',
            label: 'Εξάσκηση — 7 Τρόποι',
            desc: 'Πολλαπλής Επιλογής · Αντιστοίχιση · Κάρτες Μνήμης · Σωστό/Λάθος · Συμπλήρωση · Χρονολογία · Βίντεο.',
            en: { label: 'Practice — 7 Modes', desc: 'Multiple Choice · Matching · Flashcards · True/False · Fill in Blank · Timeline · Videos.' } },
          { type: 'naumachia', icon: '⚓',
            label: 'Ναυμαχία — Ναυτική Σύγκρουση',
            desc: 'Ναυτικές μάχες αρχαίας Ελλάδας — βύθισε τον αντίπαλο στόλο απαντώντας σωστά! Επίλεξε ύλη στον Πίνακα Παιχνιδιών.',
            en: { label: 'Naumachia — Naval Battle', desc: 'Ancient Greek naval combat — sink the enemy fleet by answering correctly! Choose content in the Games Panel.' } },
          { type: 'dig', icon: '⛏️',
            label: 'Ανασκαφή — Αρχαιολογική Εξερεύνηση',
            desc: 'Σκάψε και ανακάλυψε αρχαία ευρήματα — κάθε σωστή απάντηση αποκαλύπτει ένα θησαυρό!',
            en: { label: 'Archaeological Dig', desc: 'Excavate ancient artifacts — every correct answer uncovers a new discovery!' } },
        ] },
    ]
  },
  'gym-b': {
    label: 'Γυμνάσιο · Β΄ τάξη', labelEn: 'Middle School · 8th Grade',
    title: 'Β΄ Γυμνασίου',        titleEn: '8th Grade',
    desc:  'Επίλεξε μάθημα.',     descEn:  'Choose a subject.',
    parent: 'Γυμνάσιο', parentEn: 'Middle School', parentKey: 'gymnasio',
    subjects: [
      { id: 'logotexnia',   icon: '📖', bg: 'linear-gradient(135deg,#1A2E10,#3B6D11)',
        title: 'Λογοτεχνία',         desc: 'Νεοελληνικά λογοτεχνικά κείμενα.', count: 4,
        en: { title: 'Literature',         desc: 'Modern Greek literary texts.' } },
      { id: 'nea-ellinika', icon: '✍️', bg: 'linear-gradient(135deg,#0D2A3A,#185FA5)',
        title: 'Νεοελληνική Γλώσσα', desc: 'Γραμματική, σύνταξη και κατανόηση.', count: 5,
        en: { title: 'Modern Greek Language', desc: 'Grammar, syntax and comprehension.' } },
      { id: 'archaia',      icon: '🏛️', bg: 'linear-gradient(135deg,#2A1A08,#7A4E1A)',
        title: 'Αρχαία Ελληνικά',    desc: 'Αρχαία κείμενα, μετάφραση και γραμματική.', count: 6,
        en: { title: 'Ancient Greek',        desc: 'Ancient texts, translation and grammar.' },
        extraGames: [
          { type: 'labyrinth', icon: '🌀',
            label: 'Λαβύρινθος του Μινώταυρου',
            desc: 'Βρες τον Μινώταυρο! 7×7 ομίχλη πολέμου — απάντα ερωτήσεις γραμματικής & μυθολογίας.',
            en: { label: 'Labyrinth of the Minotaur', desc: 'Find the Minotaur! 7×7 fog of war — answer grammar & mythology questions.' } },
          { type: 'phalanx', icon: '🛡️',
            label: 'Φάλαγγα — Τακτική Μάχη',
            desc: 'Στρατηγικό παιχνίδι σε 6×6 πλέγμα κατά του Η/Υ — κάθε κίνηση απαιτεί σωστή απάντηση!',
            en: { label: 'Phalanx — Tactical Battle', desc: 'Turn-based strategy on a 6×6 grid vs AI — every move requires a correct answer!' } },
          { type: 'lyo', icon: '🏛️',
            label: 'Μαθαίνοντας το Λύω',
            desc: 'Κλίση ρημάτων — 32 επίπεδα, από Ενεστώτα Ενεργητικής έως Μετοχή. Επίλεξε επίπεδο και ξεκίνα!',
            en: { label: 'Learning: Lyo', desc: 'Verb conjugation — 32 levels, from Present Active to Participle. Pick a level and start!' } },
        ] },
      { id: 'iliada',       icon: '⚔️', bg: 'linear-gradient(135deg,#3D1A0A,#8B3E18)',
        title: 'Ιλιάδα',             desc: 'Ραψωδίες, ήρωες και νόημα του έπους.', count: 6,
        en: { title: 'Iliad',                desc: 'Rhapsodies, heroes and the meaning of the epic.' },
        extraGames: [
          { type: 'iliada-arcade', icon: '⚔️',
            label: 'Ιλιάδα Arcade',  desc: 'Πολέμα ως Αχιλλέας, Έκτωρ ή Πάτροκλος — 5 ραψωδίες, quiz μεταξύ κυμάτων.',
            en: { label: 'Iliad Arcade', desc: 'Fight as Achilles, Hector or Patroclus — 5 books, quiz between waves.' } },
          { type: 'epic-puzzle', icon: '📋',
            label: 'Χρονολόγιο — Ιλιάδα', desc: 'Βάλε τα γεγονότα της Ιλιάδας στη σωστή χρονολογική σειρά — 5 γύροι.',
            en: { label: 'Chronicle — Iliad', desc: 'Arrange Iliad events in the correct chronological order — 5 rounds.' } },
          { type: 'myth-memory', icon: '🃏',
            label: 'Mythology Memory', desc: 'Βρες τα ζεύγη — ήρωες & επίθετα της Ιλιάδας.',
            en: { label: 'Mythology Memory', desc: 'Find the pairs — heroes & epithets of the Iliad.' } },
          { type: 'rapid-fire', icon: '⚡',
            label: 'Καταιγισμός — Ιλιάδα', desc: 'Κράτα την καταιγίδα ζωντανή — άπειρες ερωτήσεις, εναλλασσόμενοι τύποι, επιλογή χρόνου!',
            en: { label: 'Kataigismos — Iliad', desc: 'Keep the storm alive — infinite questions, alternating formats, you pick the clock!' } },
          { type: 'temple-run', icon: '🏛️',
            label: 'Temple Run — Αρχαία Αγορά',
            desc: 'Τρέξε στην Αρχαία Αγορά! Αποφύγε τους πωλητές, μάζεψε δραχμές — τα ανθρωποφάγα βιβλία σε κυνηγούν!',
            en: { label: 'Temple Run — Ancient Agora', desc: 'Race through the Ancient Agora! Dodge vendors, collect drachmas — cannibalistic textbooks are on your tail!' } },
          { type: 'naumachia', icon: '⚓',
            label: 'Ναυμαχία — Ναυτική Σύγκρουση',
            desc: 'Ναυτικές μάχες αρχαίας Ελλάδας! Βύθισε τον αντίπαλο στόλο απαντώντας σωστά — επίλεξε ύλη & παίξε!',
            en: { label: 'Naumachia — Naval Battle', desc: 'Ancient Greek naval combat! Sink the enemy fleet by answering correctly — pick content & play!' } },
          { type: 'phalanx', icon: '🛡️',
            label: 'Φάλαγγα — Τακτική Μάχη',
            desc: 'Στρατηγικό παιχνίδι σε 6×6 πλέγμα κατά του Η/Υ — κατέκτησε αντίπαλες γραμμές με σωστές απαντήσεις!',
            en: { label: 'Phalanx — Tactical Battle', desc: 'Turn-based strategy on a 6×6 grid vs AI — capture enemy lines with correct answers!' } },
        ] },
      { id: 'istoria',      icon: '🗺️', bg: 'linear-gradient(135deg,#1A0D2A,#4A3890)',
        title: 'Ιστορία',            desc: 'Βυζαντινή και νεότερη ελληνική ιστορία.', count: 4,
        en: { title: 'History',              desc: 'Byzantine and modern Greek history.' },
        extraGames: [
          { type: 'history-game', icon: '🗺️',
            label: 'Εξάσκηση — 7 Τρόποι',
            desc: 'Πολλαπλής Επιλογής · Αντιστοίχιση · Κάρτες Μνήμης · Σωστό/Λάθος · Συμπλήρωση · Χρονολογία · Βίντεο.',
            en: { label: 'Practice — 7 Modes', desc: 'Multiple Choice · Matching · Flashcards · True/False · Fill in Blank · Timeline · Videos.' } },
          { type: 'naumachia', icon: '⚓',
            label: 'Ναυμαχία — Ναυτική Σύγκρουση',
            desc: 'Ναυτικές μάχες! Βύθισε τον αντίπαλο στόλο απαντώντας σωστά — επίλεξε ύλη & παίξε!',
            en: { label: 'Naumachia — Naval Battle', desc: 'Naval combat! Sink the enemy fleet by answering correctly — pick content & play!' } },
          { type: 'dig', icon: '⛏️',
            label: 'Ανασκαφή — Αρχαιολογική Εξερεύνηση',
            desc: 'Σκάψε και ανακάλυψε αρχαία ευρήματα — κάθε σωστή απάντηση αποκαλύπτει ένα νέο εύρημα!',
            en: { label: 'Archaeological Dig', desc: 'Excavate ancient artifacts — every correct answer uncovers a new discovery!' } },
        ] },
    ]
  },
  'gym-c': {
    label: 'Γυμνάσιο · Γ΄ τάξη', labelEn: 'Middle School · 9th Grade',
    title: 'Γ΄ Γυμνασίου',        titleEn: '9th Grade',
    desc:  'Επίλεξε μάθημα.',     descEn:  'Choose a subject.',
    parent: 'Γυμνάσιο', parentEn: 'Middle School', parentKey: 'gymnasio',
    subjects: [
      { id: 'logotexnia',   icon: '📖', bg: 'linear-gradient(135deg,#1A2E10,#3B6D11)',
        title: 'Λογοτεχνία',         desc: 'Νεοελληνικά λογοτεχνικά κείμενα.', count: 4,
        en: { title: 'Literature',         desc: 'Modern Greek literary texts.' } },
      { id: 'nea-ellinika', icon: '✍️', bg: 'linear-gradient(135deg,#0D2A3A,#185FA5)',
        title: 'Νεοελληνική Γλώσσα', desc: 'Γραμματική, σύνταξη και κατανόηση.', count: 5,
        en: { title: 'Modern Greek Language', desc: 'Grammar, syntax and comprehension.' } },
      { id: 'archaia',      icon: '🏛️', bg: 'linear-gradient(135deg,#2A1A08,#7A4E1A)',
        title: 'Αρχαία Ελληνικά',    desc: 'Αρχαία κείμενα, μετάφραση και γραμματική.', count: 6,
        en: { title: 'Ancient Greek',        desc: 'Ancient texts, translation and grammar.' } },
      { id: 'eleni',        icon: '🎭', bg: 'linear-gradient(135deg,#2A1018,#803040)',
        title: 'Ελένη',              desc: 'Ευριπίδης — ανάλυση και θέματα.', count: 3,
        en: { title: 'Helen',                desc: 'Euripides — analysis and themes.' } },
      { id: 'istoria',      icon: '🗺️', bg: 'linear-gradient(135deg,#1A0D2A,#4A3890)',
        title: 'Ιστορία',            desc: 'Νεότερη και σύγχρονη ελληνική ιστορία.', count: 4,
        en: { title: 'History',              desc: 'Modern and contemporary Greek history.' },
        extraGames: [
          { type: 'history-game', icon: '🗺️',
            label: 'Εξάσκηση — 7 Τρόποι',
            desc: 'Πολλαπλής Επιλογής · Αντιστοίχιση · Κάρτες Μνήμης · Σωστό/Λάθος · Συμπλήρωση · Χρονολογία · Βίντεο.',
            en: { label: 'Practice — 7 Modes', desc: 'Multiple Choice · Matching · Flashcards · True/False · Fill in Blank · Timeline · Videos.' } },
        ] },
    ]
  },
  'lyk-a': {
    label: 'Λύκειο · Α΄ τάξη', labelEn: 'High School · 10th Grade',
    title: 'Α΄ Λυκείου',       titleEn: '10th Grade',
    desc:  'Επίλεξε μάθημα.',  descEn:  'Choose a subject.',
    parent: 'Λύκειο', parentEn: 'High School', parentKey: 'lykeio',
    subjects: [
      { id: 'logotexnia',   icon: '📖', bg: 'linear-gradient(135deg,#1A2E10,#3B6D11)',
        title: 'Λογοτεχνία',                        desc: 'Νεοελληνική λογοτεχνία Α΄ Λυκείου.', count: 4,
        en: { title: 'Literature',                  desc: 'Modern Greek literature, 10th grade.' } },
      { id: 'nea-ellinika', icon: '✍️', bg: 'linear-gradient(135deg,#0D2A3A,#185FA5)',
        title: 'Νεοελληνική Γλώσσα',                desc: 'Γραμματική, σύνταξη και κατανόηση.', count: 5,
        en: { title: 'Modern Greek Language',       desc: 'Grammar, syntax and comprehension.' } },
      { id: 'archaia-thx',  icon: '🏛️', bg: 'linear-gradient(135deg,#2A1A08,#7A4E1A)',
        title: 'Αρχαία — Θουκυδίδης & Ξενοφώντας', desc: 'Μετάφραση και ερμηνεία αρχαίων κειμένων.', count: 5,
        en: { title: 'Ancient — Thucydides & Xenophon', desc: 'Translation and interpretation of ancient texts.' } },
      { id: 'istoria',      icon: '🗺️', bg: 'linear-gradient(135deg,#1A0D2A,#4A3890)',
        title: 'Ιστορία',                            desc: 'Νεότερη ελληνική και παγκόσμια ιστορία.', count: 4,
        en: { title: 'History',                     desc: 'Modern Greek and world history.' },
        extraGames: [
          { type: 'history-game', icon: '🗺️',
            label: 'Εξάσκηση — 7 Τρόποι',
            desc: 'Πολλαπλής Επιλογής · Αντιστοίχιση · Κάρτες Μνήμης · Σωστό/Λάθος · Συμπλήρωση · Χρονολογία · Βίντεο.',
            en: { label: 'Practice — 7 Modes', desc: 'Multiple Choice · Matching · Flashcards · True/False · Fill in Blank · Timeline · Videos.' } },
        ] },
    ]
  },
  'lyk-b': {
    label: 'Λύκειο · Β΄ τάξη', labelEn: 'High School · 11th Grade',
    title: 'Β΄ Λυκείου',       titleEn: '11th Grade',
    desc:  'Επίλεξε κατεύθυνση.', descEn: 'Choose a track.',
    parent: 'Λύκειο', parentEn: 'High School', parentKey: 'lykeio',
    tracks: [
      { title: 'Γενική Παιδεία', titleEn: 'General Education', subjects: [
        { id: 'logotexnia-b', icon: '📖', bg: 'linear-gradient(135deg,#1A2E10,#3B6D11)',
          title: 'Λογοτεχνία Β΄',                    desc: 'Νεοελληνική λογοτεχνία Β΄ Λυκείου.', count: 4,
          en: { title: 'Literature 2nd Year',         desc: 'Modern Greek literature, 11th grade.' } },
        { id: 'glossa-log',   icon: '✍️', bg: 'linear-gradient(135deg,#0D2A3A,#185FA5)',
          title: 'Νεοελληνική Γλώσσα & Λογοτεχνία',  desc: 'Γλώσσα και λογοτεχνία ενιαία.', count: 5,
          en: { title: 'Modern Greek Language & Literature', desc: 'Language and literature combined.' } },
        { id: 'istoria-gp',   icon: '🗺️', bg: 'linear-gradient(135deg,#1A0D2A,#4A3890)',
          title: 'Ιστορία Γενικής Παιδείας',          desc: 'Νεότερη και σύγχρονη ιστορία.', count: 4,
          en: { title: 'General History',             desc: 'Modern and contemporary history.' } },
        { id: 'antigoni',     icon: '🎭', bg: 'linear-gradient(135deg,#2A1018,#803040)',
          title: 'Αντιγόνη',                          desc: 'Σοφοκλής — ανάλυση, δομή και θέματα.', count: 3,
          en: { title: 'Antigone',                    desc: 'Sophocles — analysis, structure and themes.' } },
      ]},
      { title: 'Θεωρητική Κατεύθυνση', titleEn: 'Theoretical Track', subjects: [
        { id: 'archaia-th',  icon: '🏛️', bg: 'linear-gradient(135deg,#2A1A08,#7A4E1A)',
          title: 'Αρχαία Ελληνικά',     desc: 'Κείμενα, γραμματική και συντακτικό.', count: 6,
          en: { title: 'Ancient Greek',  desc: 'Texts, grammar and syntax.' } },
        { id: 'istoria-kat', icon: '🗺️', bg: 'linear-gradient(135deg,#1A0D2A,#4A3890)',
          title: 'Ιστορία Κατεύθυνσης', desc: 'Ιστορία για Πανελλαδικές.', count: 5,
          en: { title: 'Exam History',   desc: 'History for national exams.' },
          extraGames: [
            { type: 'istoria-g3', icon: '📜',
              label: 'Εξάσκηση — 7 Τρόποι',
              desc: 'Πολλαπλής Επιλογής · Αντιστοίχιση · Κάρτες Μνήμης · Σωστό/Λάθος · Συμπλήρωση · Χρονολογία · Βίντεο.',
              en: { label: 'Practice — 7 Modes', desc: 'Multiple Choice · Matching · Flashcards · True/False · Fill in Blank · Timeline · Videos.' } },
          ] },
        { id: 'latinika',    icon: '🔤', bg: 'linear-gradient(135deg,#082A1A,#186040)',
          title: 'Λατινικά',             desc: 'Κείμενα, μετάφραση και γραμματική.', count: 4,
          en: { title: 'Latin',          desc: 'Texts, translation and grammar.' } },
      ]}
    ]
  },
  'lyk-c': {
    label: 'Λύκειο · Γ΄ τάξη', labelEn: 'High School · 12th Grade',
    title: 'Γ΄ Λυκείου',       titleEn: '12th Grade',
    desc:  'Επίλεξε κατεύθυνση.', descEn: 'Choose a track.',
    parent: 'Λύκειο', parentEn: 'High School', parentKey: 'lykeio',
    tracks: [
      { title: 'Γενική Παιδεία', titleEn: 'General Education', subjects: [
        { id: 'logotexnia-c', icon: '📖', bg: 'linear-gradient(135deg,#1A2E10,#3B6D11)',
          title: 'Λογοτεχνία Γ΄',                    desc: 'Νεοελληνική λογοτεχνία Γ΄ Λυκείου.', count: 4,
          en: { title: 'Literature 3rd Year',         desc: 'Modern Greek literature, 12th grade.' } },
        { id: 'glossa-log',   icon: '✍️', bg: 'linear-gradient(135deg,#0D2A3A,#185FA5)',
          title: 'Νεοελληνική Γλώσσα & Λογοτεχνία',  desc: 'Γλώσσα και λογοτεχνία ενιαία.', count: 5,
          en: { title: 'Modern Greek Language & Literature', desc: 'Language and literature combined.' } },
        { id: 'istoria-gp',   icon: '🗺️', bg: 'linear-gradient(135deg,#1A0D2A,#4A3890)',
          title: 'Ιστορία Γενικής Παιδείας',          desc: 'Νεότερη και σύγχρονη ιστορία.', count: 4,
          en: { title: 'General History',             desc: 'Modern and contemporary history.' } },
        { id: 'antigoni',     icon: '🎭', bg: 'linear-gradient(135deg,#2A1018,#803040)',
          title: 'Αντιγόνη',                          desc: 'Σοφοκλής — ανάλυση, δομή και θέματα.', count: 3,
          en: { title: 'Antigone',                    desc: 'Sophocles — analysis, structure and themes.' } },
      ]},
      { title: 'Θεωρητική Κατεύθυνση', titleEn: 'Theoretical Track', subjects: [
        { id: 'archaia-th',  icon: '🏛️', bg: 'linear-gradient(135deg,#2A1A08,#7A4E1A)',
          title: 'Αρχαία Ελληνικά',     desc: 'Κείμενα, γραμματική και συντακτικό.', count: 6,
          en: { title: 'Ancient Greek',  desc: 'Texts, grammar and syntax.' } },
        { id: 'istoria-kat', icon: '🗺️', bg: 'linear-gradient(135deg,#1A0D2A,#4A3890)',
          title: 'Ιστορία Κατεύθυνσης', desc: 'Ιστορία για Πανελλαδικές.', count: 5,
          en: { title: 'Exam History',   desc: 'History for national exams.' },
          extraGames: [
            { type: 'istoria-g3', icon: '📜',
              label: 'Εξάσκηση — 7 Τρόποι',
              desc: 'Πολλαπλής Επιλογής · Αντιστοίχιση · Κάρτες Μνήμης · Σωστό/Λάθος · Συμπλήρωση · Χρονολογία · Βίντεο.',
              en: { label: 'Practice — 7 Modes', desc: 'Multiple Choice · Matching · Flashcards · True/False · Fill in Blank · Timeline · Videos.' } },
          ] },
        { id: 'latinika',    icon: '🔤', bg: 'linear-gradient(135deg,#082A1A,#186040)',
          title: 'Λατινικά',             desc: 'Κείμενα, μετάφραση και γραμματική.', count: 4,
          en: { title: 'Latin',          desc: 'Texts, translation and grammar.' } },
      ]}
    ]
  },
  'gram-nea': {
    label: 'Γραμματική · Νέα Ελληνικά', labelEn: 'Grammar · Modern Greek',
    title: 'Νέα Ελληνικά',              titleEn: 'Modern Greek',
    desc:  'Επίλεξε κατηγορία γραμματικής.', descEn: 'Choose a grammar category.',
    parent: 'Γραμματική', parentEn: 'Grammar', parentKey: 'grammatiki',
    subjects: [
      { id: 'ousiastika', icon: '📝', bg: 'linear-gradient(135deg,#0D2A3A,#185FA5)',
        title: 'Ουσιαστικά',  desc: 'Κλίση, γένος και χρήση ουσιαστικών.', count: 4,
        en: { title: 'Nouns',       desc: 'Declension, gender and use of nouns.' } },
      { id: 'antonymies', icon: '👤', bg: 'linear-gradient(135deg,#1A2E10,#3B6D11)',
        title: 'Αντωνυμίες',  desc: 'Προσωπικές, κτητικές, δεικτικές.', count: 4,
        en: { title: 'Pronouns',    desc: 'Personal, possessive, demonstrative.' } },
      { id: 'epitheta',   icon: '🔆', bg: 'linear-gradient(135deg,#2A1A08,#7A4E1A)',
        title: 'Επίθετα',     desc: 'Κλίση και βαθμοί επιθέτων.', count: 4,
        en: { title: 'Adjectives',  desc: 'Declension and degrees of adjectives.' } },
      { id: 'rimata',     icon: '⚡', bg: 'linear-gradient(135deg,#3D1A0A,#8B3E18)',
        title: 'Ρήματα',      desc: 'Συζυγίες, χρόνοι και εγκλίσεις.', count: 5,
        en: { title: 'Verbs',       desc: 'Conjugations, tenses and moods.' } },
    ]
  },
  'gram-arch': {
    label: 'Γραμματική · Αρχαία Ελληνικά', labelEn: 'Grammar · Ancient Greek',
    title: 'Αρχαία Ελληνικά',              titleEn: 'Ancient Greek',
    desc:  'Επίλεξε κατηγορία γραμματικής.', descEn: 'Choose a grammar category.',
    parent: 'Γραμματική', parentEn: 'Grammar', parentKey: 'grammatiki',
    subjects: [
      { id: 'ousiastika', icon: '📝', bg: 'linear-gradient(135deg,#0D2A3A,#185FA5)',
        title: 'Ουσιαστικά',  desc: 'Α΄, β΄, γ΄ κλίση ουσιαστικών.', count: 6,
        featuredGame: { type: 'nouns' },
        en: { title: 'Nouns',       desc: '1st, 2nd, 3rd declension nouns.' },
        extraGames: [
          { type: 'noun-tow', icon: '⚖️',
            label: 'Tug of War — Ουσιαστικά', desc: '2 ομάδες — ερωτήσεις κλίσης, το σχοινί κινείται με κάθε σωστή απάντηση.',
            en: { label: 'Tug of War — Nouns', desc: '2 teams — declension questions, the rope moves with every correct answer.' } },
          { type: 'noun-fill', icon: '✏️',
            label: 'Συμπλήρωση Κατάληξης', desc: 'Γράψε τη σωστή κατάληξη — Α΄ και Β΄ Κλίση, 9 επίπεδα.',
            en: { label: 'Fill the Ending', desc: 'Type the correct ending — 1st and 2nd declension, 9 levels.' } },
          { type: 'grammar-invaders', icon: '🚀',
            label: 'Grammar Invaders — Ουσιαστικά', desc: 'Space Invaders με λέξεις — κατέστρεψε μόνο τα σωστά ουσιαστικά!',
            en: { label: 'Grammar Invaders — Nouns', desc: 'Space Invaders with words — shoot only the correct nouns!' } },
        ] },
      { id: 'antonymies', icon: '👤', bg: 'linear-gradient(135deg,#1A2E10,#3B6D11)',
        title: 'Αντωνυμίες',  desc: 'Προσωπικές, αυτοπαθείς, αναφορικές.', count: 4,
        featuredGame: { type: 'antonymies' },
        en: { title: 'Pronouns',    desc: 'Personal, reflexive, relative.' } },
      { id: 'epitheta',   icon: '🔆', bg: 'linear-gradient(135deg,#2A1A08,#7A4E1A)',
        title: 'Επίθετα',     desc: 'Τρικατάληκτα, δικατάληκτα και παραθετικά.', count: 5,
        featuredGame: { type: 'paratheta' },
        en: { title: 'Adjectives',  desc: 'Three-ending, two-ending adjectives and degrees of comparison.' },
        extraGames: [
          { type: 'klisi-epitheton', icon: '🔤',
            label: 'Κλίση Επιθέτων', desc: 'Τρικατάληκτα, δικατάληκτα & ανώμαλα — 9 επίπεδα, πλήρης κλίση.',
            en: { label: 'Adjective Declension', desc: 'Three-ending, two-ending & irregular adjectives — 9 levels, full declension.' } },
          { type: 'paratheta', icon: '🔼',
            label: 'Παραθετικά Επιθέτων', desc: 'Σχημάτισε συγκριτικό & υπερθετικό — ομαλά και ανώμαλα επίθετα, 10 επίπεδα.',
            en: { label: 'Degrees of Adjectives', desc: 'Form comparative & superlative — regular and irregular adjectives, 10 levels.' } },
        ] },
      { id: 'rimata', icon: '⚡', bg: 'linear-gradient(135deg,#3D1A0A,#8B3E18)',
        title: 'Ρήματα', desc: 'Συζυγίες, χρόνοι, εγκλίσεις και φωνές.', count: 7,
        featuredGame: { type: 'lyo' },
        en: { title: 'Verbs', desc: 'Conjugations, tenses, moods and voices.' },
        extraGames: [
          { type: 'pathitiko', icon: '⚗️',
            label: 'Παθητικός Μέλλοντας & Αόριστος', desc: 'Παθητική φωνή — Μέλλοντας · Αόριστος · Βασικά & Αφωνόληκτα — 23 επίπεδα',
            en: { label: 'Passive Future & Aorist', desc: 'Passive voice — Future · Aorist · Regular & Mute-ending — 23 levels' } },
          { type: 'afwnolekta', icon: '🔤',
            label: 'Αφωνόληκτα', desc: 'Μέλλοντας, Αόριστος, Παρακείμενος — 10 ρήματα, πλήρης κλίση',
            en: { label: 'Mute-ending Verbs', desc: 'Future, Aorist, Perfect — 10 verbs, full conjugation' } },
          { type: 'aoristos-b', icon: '📜',
            label: 'Αόριστος Β΄', desc: '20 ρήματα με ανώμαλο αόριστο β΄ — όλες εγκλίσεις',
            en: { label: '2nd Aorist', desc: '20 verbs with irregular 2nd aorist — all moods' } },
          { type: 'rimata-mi',  icon: '⚙️',
            label: 'Ρήματα -μι', desc: 'δείκνυμι · δίδωμι · τίθημι · ἵστημι · ἵημι',
            en: { label: '-mi Verbs', desc: 'δείκνυμι · δίδωμι · τίθημι · ἵστημι · ἵημι' } },
          { type: 'synirimmena', icon: '🔗',
            label: 'Συνηρημένα Ρήματα', desc: 'τιμῶ · ποιῶ · δηλῶ — συναίρεση και κλίση, 3 συζυγίες',
            en: { label: 'Contracted Verbs', desc: 'τιμῶ · ποιῶ · δηλῶ — contraction and conjugation, 3 paradigms' } },
          { type: 'anwmala-rimata', icon: '⚠️',
            label: 'Ανώμαλα Ρήματα', desc: 'Ανώμαλοι τύποι — εἰμί, εἶμι, φημί, οἶδα και άλλα',
            en: { label: 'Irregular Verbs', desc: 'Irregular forms — εἰμί, εἶμι, φημί, οἶδα and others' } },
          { type: 'klisi-rimaton', icon: '🔱',
            label: 'Κλίση εἶμι · φημί · οἶδα', desc: 'Πλήρης κλίση — Οριστική, Υποτακτική, Ευκτική, Προστακτική, Μετοχή — 4 τρόποι',
            en: { label: 'Conjugation: εἶμι · φημί · οἶδα', desc: 'Full paradigms — Indicative, Subjunctive, Optative, Imperative, Participle — 4 modes' } },
          { type: 'eimi', icon: '⚡',
            label: 'Κλίση εἰμί — «είμαι»', desc: 'Καρτέλες · Κουίζ · Πίνακας — Ενεστώτας, Παρατατικός, Μέλλοντας, Υποτακτική, Ευκτική',
            en: { label: 'Conjugation: εἰμί — "to be"', desc: 'Flashcards · Quiz · Table — Present, Imperfect, Future, all moods' } },
          { type: 'grammar-invaders', icon: '🚀',
            label: 'Grammar Invaders — Ρήματα', desc: 'Space Invaders με λέξεις — κατέστρεψε μόνο τους σωστούς τύπους!',
            en: { label: 'Grammar Invaders — Verbs', desc: 'Space Invaders with words — shoot only the correct verb forms!' } },
          { type: 'rapid-fire', icon: '⚡',
            label: 'Καταιγισμός — Γραμματική', desc: 'Κράτα την καταιγίδα γραμματικής ζωντανή — άπειρες ερωτήσεις, εναλλασσόμενοι τύποι, επιλογή χρόνου!',
            en: { label: 'Kataigismos — Grammar', desc: 'Keep the grammar storm alive — infinite questions, alternating formats, you pick the clock!' } },
          { type: 'phalanx', icon: '🛡️',
            label: 'Φάλαγγα — Γραμματική',
            desc: 'Στρατηγικό παιχνίδι κατά του Η/Υ — κατέκτησε γραμμές απαντώντας σωστά σε ρήματα & κλίσεις!',
            en: { label: 'Phalanx — Grammar', desc: 'Strategy game vs AI — capture lines by answering verb conjugation questions correctly!' } },
          { type: 'labyrinth', icon: '🌀',
            label: 'Λαβύρινθος — Γραμματική',
            desc: 'Εξερεύνησε τον λαβύρινθο απαντώντας ερωτήσεις γραμματικής αρχαίων ελληνικών!',
            en: { label: 'Labyrinth — Grammar', desc: 'Explore the labyrinth by answering ancient Greek grammar questions!' } },
        ]
      },
    ]
  },
  'gram-lat': {
    label: 'Γραμματική · Λατινικά', labelEn: 'Grammar · Latin',
    title: 'Λατινικά',              titleEn: 'Latin',
    desc:  'Επίλεξε κατηγορία λατινικής γραμματικής.', descEn: 'Choose a Latin grammar category.',
    parent: 'Γραμματική', parentEn: 'Grammar', parentKey: 'grammatiki',
    subjects: [
      { id: 'ousiastika', icon: '📝', bg: 'linear-gradient(135deg,#0D2A3A,#185FA5)',
        title: 'Ουσιαστικά',  desc: 'Α΄ έως ε΄ κλίση ουσιαστικών.', count: 4,
        en: { title: 'Nouns',       desc: '1st to 5th declension nouns.' },
        extraGames: [
          { type: 'lat-nouns', icon: '🏛️',
            label: 'Κλίση Λατινικών Ουσιαστικών', desc: '52 ουσιαστικά · Α΄–Ε΄ κλίση · 6 πτώσεις · MC / Συμπλήρωση / Αντιστοίχιση',
            en: { label: 'Latin Noun Declension', desc: '52 nouns · 1st–5th declension · 6 cases · MC / Fill-in / Match' } },
          { type: 'lat-nouns-kata', icon: '📜',
            label: 'Ουσιαστικά ανά Κείμενο', desc: 'Επίλεξε κείμενα 3–45 · κλίνε τα ουσιαστικά τους · 6 πτώσεις · MC / Συμπλήρωση / Αντιστοίχιση',
            en: { label: 'Nouns by Text', desc: 'Select texts 3–45 · decline their nouns · 6 cases · MC / Fill-in / Match' } },
          { type: 'lat-nouns-kata-theory', icon: '📖',
            label: 'Ουσιαστικά — Θεωρία & Μελέτη', desc: 'Πίνακες κλίσης · Συμπλήρωση · Αναγνώριση τύπου · Κανόνες — ανά κείμενο',
            en: { label: 'Nouns — Theory & Study', desc: 'Paradigm tables · fill-in · parse the form · rules — by text' } },
        ] },
      { id: 'antonymies', icon: '👤', bg: 'linear-gradient(135deg,#1A2E10,#3B6D11)',
        title: 'Αντωνυμίες',  desc: 'Προσωπικές, κτητικές, δεικτικές.', count: 4,
        en: { title: 'Pronouns',    desc: 'Personal, possessive, demonstrative.' },
        extraGames: [
          { type: 'lat-antonymies', icon: '👤',
            label: 'Κλίση Λατινικών Αντωνυμιών', desc: 'Προσωπικές · κτητικές · δεικτικές · αναφορικές · ερωτηματικές · 6 πτώσεις',
            en: { label: 'Latin Pronoun Declension', desc: 'Personal · possessive · demonstrative · relative · interrogative · 6 cases' } },
          { type: 'lat-antonymies-theory', icon: '📖',
            label: 'Αντωνυμίες — Θεωρία & Μελέτη', desc: 'Πίνακες κλίσης · Συμπλήρωση πίνακα · Αναγνώριση τύπου · Κανόνες',
            en: { label: 'Pronouns — Theory & Study', desc: 'Paradigm tables · Fill-in tables · Form identification · Rules' } },
        ] },
      { id: 'epitheta',   icon: '🔆', bg: 'linear-gradient(135deg,#2A1A08,#7A4E1A)',
        title: 'Επίθετα',     desc: 'Α΄/β΄ κλίση και γ΄ κλίση.', count: 4,
        en: { title: 'Adjectives',  desc: '1st/2nd and 3rd declension.' },
        extraGames: [
          { type: 'lat-epitheta', icon: '🔆',
            label: 'Κλίση Λατινικών Επιθέτων', desc: 'Β΄/Γ΄ κλίση · παραθετικά · 3 γένη · 6 πτώσεις · MC / Συμπλήρωση',
            en: { label: 'Latin Adjective Declension', desc: '2nd/3rd decl. · degrees · 3 genders · 6 cases · MC / Fill-in' } },
          { type: 'lat-epitheta-kata', icon: '📜',
            label: 'Επίθετα ανά Κείμενο', desc: '96 επίθετα · Επίλεξε κείμενα 3–45 · ① Κλίση επιθέτων · ② Παραθετικά (σχηματισμός & κλίση, ομαλά & ανώμαλα)',
            en: { label: 'Adjectives by Text', desc: '96 adjectives · Select texts 3–45 · ① Declension · ② Degrees of comparison (formation & declension, regular & irregular)' } },
          { type: 'lat-epitheta-kata-theory', icon: '📖',
            label: 'Επίθετα — Θεωρία & Μελέτη', desc: 'Πίνακες κλίσης · Παραθετικά (σχηματισμός & κλίση) · Συμπλήρωση · Αναγνώριση τύπου · Κανόνες',
            en: { label: 'Adjectives — Theory & Study', desc: 'Paradigm tables · Degrees (formation & declension) · Fill-in · Form identification · Rules' } },
        ] },
      { id: 'rimata',     icon: '⚡', bg: 'linear-gradient(135deg,#3D1A0A,#8B3E18)',
        title: 'Ρήματα',      desc: 'Τέσσερις συζυγίες, χρόνοι και φωνές.', count: 6,
        en: { title: 'Verbs',       desc: 'Four conjugations, tenses and voices.' },
        extraGames: [
          { type: 'lat-verbs', icon: '⚡',
            label: 'Κλίση Λατινικών Ρημάτων', desc: '15 ρήματα · 4 συζυγίες · Ενεργ. & Παθ. φωνή · Χρόνοι & εγκλίσεις',
            en: { label: 'Latin Verb Conjugation', desc: '15 verbs · 4 conjugations · Active & Passive voice · Tenses & moods' } },
          { type: 'lat-kata', icon: '📋',
            label: 'Ρήματα ανά Κείμενο', desc: '339 ρήματα · Επίλεξε κείμενα 16–50 · Συμπλήρωσε Ενεστ. · Παρακ. · Σούπ. · Απαρ.',
            en: { label: 'Verbs by Text', desc: '339 verbs · Select texts 16–50 · Fill in Pres. · Perf. · Sup. · Inf.' } },
          { type: 'lat-anwmala', icon: '🌀',
            label: 'Ανώμαλα Ρήματα', desc: '17 ρήματα · possum · eo · fero · fio · volo · nolo · malo · nequeo + ανώμαλα · Επίλεξε ρήμα/ρήματα · Πλήρη παραδείγματα',
            en: { label: 'Irregular Verbs', desc: '17 verbs · possum · eo · fero · fio · volo · nolo · malo · nequeo + more · Pick verb(s) · Full paradigms' } },
          { type: 'lat-anwmala-theory', icon: '📖',
            label: 'Ανώμαλα Ρήματα — Θεωρία', desc: 'Σημειώσεις ανά ρήμα · possum · eo · fero · fio · volo/nolo/malo · nequeo · Κάρτες κανόνων',
            en: { label: 'Irregular Verbs — Theory', desc: 'Notes per verb · possum · eo · fero · fio · volo/nolo/malo · nequeo · Rule cards' } },
        ] },
    ]
  },
};

// ── DEFAULT GAMES ──
// Only the Trivia card — all other placeholder modes removed.
// Tug of War lives inside the Trivia page as a selectable mode.
const DEFAULT_GAMES = [
  { tags: 'free solo multi', banner: '🏆', bg: 'linear-gradient(135deg,#2A1008,#7A3010)',
    free: true,  multi: false, locked: false, isTrivia: true,
    title: 'Ιλιάδα Trivia',    titleEn: 'Iliad Trivia',
    desc:  'Trivia & Tug of War — πολλαπλής επιλογής ή αγώνας ομάδων.', descEn: 'Trivia & Tug of War — multiple choice or team battle.',
    tags2: ['Μόνος','Multiplayer'], tags2En: ['Solo','Multiplayer'] },
];

// ── BROWSE page structure ──
const BROWSE_SECTIONS = {
  root: [
    { key: 'dimotiko',   label: 'Δημοτικό',   labelEn: 'Primary School',
      icon: '🏫', bg: 'linear-gradient(135deg,#1A2A1A,#3B6D3B)',
      desc: 'Α΄ έως ΣΤ΄ Δημοτικού', descEn: '1st to 6th Grade', disabled: true },
    { key: 'gymnasio',   label: 'Γυμνάσιο',   labelEn: 'Middle School',
      icon: '📚', bg: 'linear-gradient(135deg,#0D2A3A,#185FA5)',
      desc: 'Α΄, Β΄, Γ΄ Γυμνασίου', descEn: '7th, 8th, 9th Grade' },
    { key: 'lykeio',     label: 'Λύκειο',      labelEn: 'High School',
      icon: '🎓', bg: 'linear-gradient(135deg,#3D1A0A,#8B3E18)',
      desc: 'Α΄, Β΄, Γ΄ Λυκείου', descEn: '10th, 11th, 12th Grade' },
    { key: 'grammatiki', label: 'Γραμματική',  labelEn: 'Grammar',
      icon: '🔤', bg: 'linear-gradient(135deg,#082A1A,#186040)',
      desc: 'Νέα Ελληνικά, Αρχαία, Λατινικά', descEn: 'Modern Greek, Ancient Greek, Latin' },
  ],
  gymnasio: [
    { key: 'gym-a', label: 'Α΄ Γυμνασίου', labelEn: '7th Grade',
      icon: '📖', bg: 'linear-gradient(135deg,#0D2A3A,#185FA5)',
      desc: '5 μαθήματα', descEn: '5 subjects' },
    { key: 'gym-b', label: 'Β΄ Γυμνασίου', labelEn: '8th Grade',
      icon: '⚔️', bg: 'linear-gradient(135deg,#3D1A0A,#8B3E18)',
      desc: '5 μαθήματα', descEn: '5 subjects' },
    { key: 'gym-c', label: 'Γ΄ Γυμνασίου', labelEn: '9th Grade',
      icon: '🎭', bg: 'linear-gradient(135deg,#2A1018,#803040)',
      desc: '5 μαθήματα', descEn: '5 subjects' },
  ],
  lykeio: [
    { key: 'lyk-a', label: 'Α΄ Λυκείου', labelEn: '10th Grade',
      icon: '📖', bg: 'linear-gradient(135deg,#1A2E10,#3B6D11)',
      desc: '4 μαθήματα', descEn: '4 subjects' },
    { key: 'lyk-b', label: 'Β΄ Λυκείου', labelEn: '11th Grade',
      icon: '📐', bg: 'linear-gradient(135deg,#0D2A3A,#185FA5)',
      desc: 'Γενική + Θεωρητική', descEn: 'General + Theoretical' },
    { key: 'lyk-c', label: 'Γ΄ Λυκείου', labelEn: '12th Grade',
      icon: '🏆', bg: 'linear-gradient(135deg,#3D1A0A,#8B3E18)',
      desc: 'Γενική + Θεωρητική', descEn: 'General + Theoretical' },
  ],
  grammatiki: [
    { key: 'gram-nea',  label: 'Νέα Ελληνικά',    labelEn: 'Modern Greek',
      icon: '✍️', bg: 'linear-gradient(135deg,#0D2A3A,#185FA5)',
      desc: '4 κατηγορίες', descEn: '4 categories' },
    { key: 'gram-arch', label: 'Αρχαία Ελληνικά', labelEn: 'Ancient Greek',
      icon: '🏛️', bg: 'linear-gradient(135deg,#2A1A08,#7A4E1A)',
      desc: '4 κατηγορίες', descEn: '4 categories' },
    { key: 'gram-lat',  label: 'Λατινικά',         labelEn: 'Latin',
      icon: '🔤', bg: 'linear-gradient(135deg,#082A1A,#186040)',
      desc: '4 κατηγορίες', descEn: '4 categories' },
  ],
};
