// Latin Verb Conjugation Data — 4 conjugations, active + passive
// Forms stored per tense-voice-mood: array of 6 [sg1,sg2,sg3,pl1,pl2,pl3]
// Keys: act_ind_pres/ipf/fut/prf/plpf | act_sub_pres/ipf | pas_ind_pres/ipf/fut | pas_sub_pres/ipf

const LAT_V_TENSES = {
  pres:'Ενεστώτας', ipf:'Παρατατικός', fut:'Μέλλοντας',
  prf:'Παρακείμενος', plpf:'Υπερσυντελικός',
};
const LAT_V_MOODS  = { ind:'Οριστική', sub:'Υποτακτική' };
const LAT_V_VOICES = { act:'Ενεργητική', pas:'Παθητική' };
const LAT_V_PERSONS = ['α΄ εν.','β΄ εν.','γ΄ εν.','α΄ πλ.','β΄ πλ.','γ΄ πλ.'];
const LAT_V_CONJ_LABELS = {1:'Α΄ Συζυγία',2:'Β΄ Συζυγία',3:'Γ΄ Συζυγία',4:'Δ΄ Συζυγία'};

const LAT_V_DB = [

  // ═══ Α΄ ΣΥΖΥΓΙΑ (-are) ═══
  { inf:'amare', meaning:'αγαπώ', conj:1,
    act_ind_pres:  ['amo','amas','amat','amamus','amatis','amant'],
    act_ind_ipf:   ['amabam','amabas','amabat','amabamus','amabatis','amabant'],
    act_ind_fut:   ['amabo','amabis','amabit','amabimus','amabitis','amabunt'],
    act_ind_prf:   ['amavi','amavisti','amavit','amavimus','amavistis','amaverunt'],
    act_ind_plpf:  ['amaveram','amaveras','amaverat','amaveramus','amaveratis','amaverant'],
    act_sub_pres:  ['amem','ames','amet','amemus','ametis','ament'],
    act_sub_ipf:   ['amarem','amares','amaret','amaremus','amaretis','amarent'],
    pas_ind_pres:  ['amor','amaris','amatur','amamur','amamini','amantur'],
    pas_ind_ipf:   ['amabar','amabaris','amabatur','amabamur','amabamini','amabantur'],
    pas_ind_fut:   ['amabor','amaberis','amabitur','amabimur','amabimini','amabuntur'],
    pas_sub_pres:  ['amer','ameris','ametur','amemur','amemini','amentur'],
    pas_sub_ipf:   ['amarer','amareris','amaretur','amaremur','amaremini','amarentur'],
  },
  { inf:'laudare', meaning:'επαινώ', conj:1,
    act_ind_pres:  ['laudo','laudas','laudat','laudamus','laudatis','laudant'],
    act_ind_ipf:   ['laudabam','laudabas','laudabat','laudabamus','laudabatis','laudabant'],
    act_ind_fut:   ['laudabo','laudabis','laudabit','laudabimus','laudabitis','laudabunt'],
    act_ind_prf:   ['laudavi','laudavisti','laudavit','laudavimus','laudavistis','laudaverunt'],
    act_ind_plpf:  ['laudaveram','laudaveras','laudaverat','laudaveramus','laudaveratis','laudaverant'],
    act_sub_pres:  ['laudem','laudes','laudet','laudemus','laudetis','laudent'],
    act_sub_ipf:   ['laudarem','laudares','laudaret','laudaremus','laudaretis','laudarent'],
    pas_ind_pres:  ['laudor','laudaris','laudatur','laudamur','laudamini','laudantur'],
    pas_ind_ipf:   ['laudabar','laudabaris','laudabatur','laudabamur','laudabamini','laudabantur'],
    pas_ind_fut:   ['laudabor','laudaberis','laudabitur','laudabimur','laudabimini','laudabuntur'],
    pas_sub_pres:  ['lauder','lauderis','laudetur','laudemur','laudemini','laudentur'],
    pas_sub_ipf:   ['laudarer','laudareris','laudaretur','laudaremur','laudaremini','laudarentur'],
  },
  { inf:'vocare', meaning:'καλώ', conj:1,
    act_ind_pres:  ['voco','vocas','vocat','vocamus','vocatis','vocant'],
    act_ind_ipf:   ['vocabam','vocabas','vocabat','vocabamus','vocabatis','vocabant'],
    act_ind_fut:   ['vocabo','vocabis','vocabit','vocabimus','vocabitis','vocabunt'],
    act_ind_prf:   ['vocavi','vocavisti','vocavit','vocavimus','vocavistis','vocaverunt'],
    act_ind_plpf:  ['vocaveram','vocaveras','vocaverat','vocaveramus','vocaveratis','vocaverant'],
    act_sub_pres:  ['vocem','voces','vocet','vocemus','vocetis','vocent'],
    act_sub_ipf:   ['vocarem','vocares','vocaret','vocaremus','vocaretis','vocarent'],
    pas_ind_pres:  ['vocor','vocaris','vocatur','vocamur','vocamini','vocantur'],
    pas_ind_ipf:   ['vocabar','vocabaris','vocabatur','vocabamur','vocabamini','vocabantur'],
    pas_ind_fut:   ['vocabor','vocaberis','vocabitur','vocabimur','vocabimini','vocabuntur'],
    pas_sub_pres:  ['vocer','voceris','vocetur','vocemur','vocemini','vocentur'],
    pas_sub_ipf:   ['vocarer','vocareris','vocaretur','vocaremur','vocaremini','vocarentur'],
  },
  { inf:'portare', meaning:'μεταφέρω', conj:1,
    act_ind_pres:  ['porto','portas','portat','portamus','portatis','portant'],
    act_ind_ipf:   ['portabam','portabas','portabat','portabamus','portabatis','portabant'],
    act_ind_fut:   ['portabo','portabis','portabit','portabimus','portabitis','portabunt'],
    act_ind_prf:   ['portavi','portavisti','portavit','portavimus','portavistis','portaverunt'],
    act_ind_plpf:  ['portaveram','portaveras','portaverat','portaveramus','portaveratis','portaverant'],
    act_sub_pres:  ['portem','portes','portet','portemus','portetis','portent'],
    act_sub_ipf:   ['portarem','portares','portaret','portaremus','portaretis','portarent'],
    pas_ind_pres:  ['portor','portaris','portatur','portamur','portamini','portantur'],
    pas_ind_ipf:   ['portabar','portabaris','portabatur','portabamur','portabamini','portabantur'],
    pas_ind_fut:   ['portabor','portaberis','portabitur','portabimur','portabimini','portabuntur'],
    pas_sub_pres:  ['porter','porteris','portetur','portemur','portemini','portentur'],
    pas_sub_ipf:   ['portarer','portareris','portaretur','portaremur','portaremini','portarentur'],
  },

  // ═══ Β΄ ΣΥΖΥΓΙΑ (-ere / -ēre) ═══
  { inf:'delere', meaning:'καταστρέφω', conj:2,
    act_ind_pres:  ['deleo','deles','delet','delemus','deletis','delent'],
    act_ind_ipf:   ['delebam','delebas','delebat','delebamus','delebatis','delebant'],
    act_ind_fut:   ['delebo','delebis','delebit','delebimus','delebitis','delebunt'],
    act_ind_prf:   ['delevi','delevisti','delevit','delevimus','delevistis','deleverunt'],
    act_ind_plpf:  ['deleveram','deleveras','deleverat','deleveramus','deleveratis','deleverant'],
    act_sub_pres:  ['deleam','deleas','deleat','deleamus','deleatis','deleant'],
    act_sub_ipf:   ['delerem','deleres','deleret','deleremus','deleretis','delerent'],
    pas_ind_pres:  ['deleor','deleris','deletur','delemur','delemini','delentur'],
    pas_ind_ipf:   ['delebar','delebaris','delebatur','delebamur','delebamini','delebantur'],
    pas_ind_fut:   ['delebor','deleberis','delebitur','delebimur','delebimini','delebuntur'],
    pas_sub_pres:  ['delear','delearis','deleatur','deleamur','deleamini','deleantur'],
    pas_sub_ipf:   ['delerer','delereris','deleretur','deleremur','deleremini','delerentur'],
  },
  { inf:'habere', meaning:'έχω', conj:2,
    act_ind_pres:  ['habeo','habes','habet','habemus','habetis','habent'],
    act_ind_ipf:   ['habebam','habebas','habebat','habebamus','habebatis','habebant'],
    act_ind_fut:   ['habebo','habebis','habebit','habebimus','habebitis','habebunt'],
    act_ind_prf:   ['habui','habuisti','habuit','habuimus','habuistis','habuerunt'],
    act_ind_plpf:  ['habueram','habueras','habuerat','habueramus','habueratis','habuerant'],
    act_sub_pres:  ['habeam','habeas','habeat','habeamus','habeatis','habeant'],
    act_sub_ipf:   ['haberem','haberes','haberet','haberemus','haberetis','haberent'],
    pas_ind_pres:  ['habeor','haberis','habetur','habemur','habemini','habentur'],
    pas_ind_ipf:   ['habebar','habebaris','habebatur','habebamur','habebamini','habebantur'],
    pas_ind_fut:   ['habebor','habeberis','hadebitur','habebimur','habebimini','habebuntur'],
    pas_sub_pres:  ['habear','habearis','habeatur','habeamur','habeamini','habeantur'],
    pas_sub_ipf:   ['haberer','habereris','haberetur','haberemur','haberemini','haberentur'],
  },
  { inf:'videre', meaning:'βλέπω', conj:2,
    act_ind_pres:  ['video','vides','videt','videmus','videtis','vident'],
    act_ind_ipf:   ['videbam','videbas','videbat','videbamus','videbatis','videbant'],
    act_ind_fut:   ['videbo','videbis','videbit','videbimus','videbitis','videbunt'],
    act_ind_prf:   ['vidi','vidisti','vidit','vidimus','vidistis','viderunt'],
    act_ind_plpf:  ['videram','videras','viderat','videramus','videratis','viderant'],
    act_sub_pres:  ['videam','videas','videat','videamus','videatis','videant'],
    act_sub_ipf:   ['viderem','videres','videret','videremus','videretis','viderent'],
    pas_ind_pres:  ['videor','videris','videtur','videmur','videmini','videntur'],
    pas_ind_ipf:   ['videbar','videbaris','videbatur','videbamur','videbamini','videbantur'],
    pas_ind_fut:   ['videbor','videberis','videbitur','videbimur','videbimini','videbuntur'],
    pas_sub_pres:  ['videar','videaris','videatur','videamur','videamini','videantur'],
    pas_sub_ipf:   ['viderer','videreris','videretur','videremur','videremini','viderentur'],
  },
  { inf:'docere', meaning:'διδάσκω', conj:2,
    act_ind_pres:  ['doceo','doces','docet','docemus','docetis','docent'],
    act_ind_ipf:   ['docebam','docebas','docebat','docebamus','docebatis','docebant'],
    act_ind_fut:   ['docebo','docebis','docebit','docebimus','docebitis','docebunt'],
    act_ind_prf:   ['docui','docuisti','docuit','docuimus','docuistis','docuerunt'],
    act_ind_plpf:  ['docueram','docueras','docuerat','docueramus','docueratis','docuerant'],
    act_sub_pres:  ['doceam','doceas','doceat','doceamus','doceatis','doceant'],
    act_sub_ipf:   ['docerem','doceres','doceret','doceremus','doceretis','docerent'],
    pas_ind_pres:  ['doceor','doceris','docetur','docemur','docemini','docentur'],
    pas_ind_ipf:   ['docebar','docebaris','docebatur','docebamur','docebamini','docebantur'],
    pas_ind_fut:   ['docebor','doceberis','docebitur','docebimur','docebimini','docebuntur'],
    pas_sub_pres:  ['docear','docearis','doceatur','doceamur','doceamini','doceantur'],
    pas_sub_ipf:   ['docerer','docereris','doceretur','doceremur','doceremini','docerentur'],
  },

  // ═══ Γ΄ ΣΥΖΥΓΙΑ (-ere) ═══
  { inf:'legere', meaning:'διαβάζω', conj:3,
    act_ind_pres:  ['lego','legis','legit','legimus','legitis','legunt'],
    act_ind_ipf:   ['legebam','legebas','legebat','legebamus','legebatis','legebant'],
    act_ind_fut:   ['legam','leges','leget','legemus','legetis','legent'],
    act_ind_prf:   ['legi','legisti','legit','legimus','legistis','legerunt'],
    act_ind_plpf:  ['legeram','legeras','legerat','legeramus','legeratis','legerant'],
    act_sub_pres:  ['legam','legas','legat','legamus','legatis','legant'],
    act_sub_ipf:   ['legerem','legeres','legeret','legeremus','legeretis','legerent'],
    pas_ind_pres:  ['legor','legeris','legitur','legimur','legimini','leguntur'],
    pas_ind_ipf:   ['legebar','legebaris','legebatur','legebamur','legebamini','legebantur'],
    pas_ind_fut:   ['legar','legeris','legetur','legemur','legemini','legentur'],
    pas_sub_pres:  ['legar','legaris','legatur','legamur','legamini','legantur'],
    pas_sub_ipf:   ['legerer','legereris','legeretur','legeremur','legeremini','legerentur'],
  },
  { inf:'scribere', meaning:'γράφω', conj:3,
    act_ind_pres:  ['scribo','scribis','scribit','scribimus','scribitis','scribunt'],
    act_ind_ipf:   ['scribebam','scribebas','scribebat','scribebamus','scribebatis','scribebant'],
    act_ind_fut:   ['scribam','scribes','scribet','scribemus','scribetis','scribent'],
    act_ind_prf:   ['scripsi','scripsisti','scripsit','scripsimus','scripsistis','scripserunt'],
    act_ind_plpf:  ['scripseram','scripseras','scripserat','scripseramus','scripseratis','scripserant'],
    act_sub_pres:  ['scribam','scribas','scribat','scribamus','scribatis','scribant'],
    act_sub_ipf:   ['scriberem','scriberes','scriberet','scriberemus','scribereutis','scriberent'],
    pas_ind_pres:  ['scribor','scriberis','scribitur','scribimur','scribimini','scribuntur'],
    pas_ind_ipf:   ['scribebar','scribebaris','scribebatur','scribebamur','scribebamini','scribebantur'],
    pas_ind_fut:   ['scribar','scriberis','scribetur','scribemur','scribemini','scribentur'],
    pas_sub_pres:  ['scribar','scribaris','scribatur','scribamur','scribamini','scribantur'],
    pas_sub_ipf:   ['scriberer','scribereris','scriberetur','scriberetur','scriberetur','scriberetur'],
  },
  { inf:'ducere', meaning:'οδηγώ', conj:3,
    act_ind_pres:  ['duco','ducis','ducit','ducimus','ducitis','ducunt'],
    act_ind_ipf:   ['ducebam','ducebas','ducebat','ducebamus','ducebatis','ducebant'],
    act_ind_fut:   ['ducam','duces','ducet','ducemus','ducetis','ducent'],
    act_ind_prf:   ['duxi','duxisti','duxit','duximus','duxistis','duxerunt'],
    act_ind_plpf:  ['duxeram','duxeras','duxerat','duxeramus','duxeratis','duxerant'],
    act_sub_pres:  ['ducam','ducas','ducat','ducamus','ducatis','ducant'],
    act_sub_ipf:   ['ducerem','duceres','duceret','duceremus','duceretis','ducerent'],
    pas_ind_pres:  ['ducor','duceris','ducitur','ducimur','ducimini','ducuntur'],
    pas_ind_ipf:   ['ducebar','ducebaris','ducebatur','ducebamur','ducebamini','ducebantur'],
    pas_ind_fut:   ['ducar','duceris','ducetur','ducemur','ducemini','ducentur'],
    pas_sub_pres:  ['ducar','ducaris','ducatur','ducamur','ducamini','ducantur'],
    pas_sub_ipf:   ['ducerer','ducereris','duceretur','duceremur','duceremini','ducerentur'],
  },
  { inf:'mittere', meaning:'στέλνω', conj:3,
    act_ind_pres:  ['mitto','mittis','mittit','mittimus','mittitis','mittunt'],
    act_ind_ipf:   ['mittebam','mittebas','mittebat','mittebamus','mittebatis','mittebant'],
    act_ind_fut:   ['mittam','mittes','mittet','mittemus','mittetis','mittent'],
    act_ind_prf:   ['misi','misisti','misit','misimus','misistis','miserunt'],
    act_ind_plpf:  ['miseram','miseras','miserat','miseramus','miseratis','miserant'],
    act_sub_pres:  ['mittam','mittas','mittat','mittamus','mittatis','mittant'],
    act_sub_ipf:   ['mitterem','mitteres','mitteret','mitteremus','mitteretis','mitterent'],
    pas_ind_pres:  ['mittor','mitteris','mittitur','mittimur','mittimini','mittuntur'],
    pas_ind_ipf:   ['mittebar','mittebaris','mittebatur','mittebamur','mittebamini','mittebantur'],
    pas_ind_fut:   ['mittar','mitteris','mittetur','mittemur','mittemini','mittentur'],
    pas_sub_pres:  ['mittar','mittaris','mittatur','mittamur','mittamini','mittantur'],
    pas_sub_ipf:   ['mitterer','mittereris','mitteretur','mutteremur','mitteremini','mitterentur'],
  },

  // ═══ Δ΄ ΣΥΖΥΓΙΑ (-ire) ═══
  { inf:'audire', meaning:'ακούω', conj:4,
    act_ind_pres:  ['audio','audis','audit','audimus','auditis','audiunt'],
    act_ind_ipf:   ['audiebam','audiebas','audiebat','audiebamus','audiebatis','audiebant'],
    act_ind_fut:   ['audiam','audies','audiet','audiemus','audietis','audient'],
    act_ind_prf:   ['audivi','audivisti','audivit','audivimus','audivistis','audiverunt'],
    act_ind_plpf:  ['audiveram','audiveras','audiverat','audiveramus','audiveratis','audiverant'],
    act_sub_pres:  ['audiam','audias','audiat','audiamus','audiatis','audiant'],
    act_sub_ipf:   ['audirem','audires','audiret','audiremus','audiretis','audirent'],
    pas_ind_pres:  ['audior','audiris','auditur','audimur','audimini','audiuntur'],
    pas_ind_ipf:   ['audiebar','audiebaris','audiebatur','audiebamur','audiebamini','audiebantur'],
    pas_ind_fut:   ['audiar','audieris','audietur','audiemur','audiemini','audientur'],
    pas_sub_pres:  ['audiar','audiaris','audiatur','audiamur','audiamini','audiantur'],
    pas_sub_ipf:   ['audirer','audireris','audiretur','audiremur','audiremini','audirentur'],
  },
  { inf:'venire', meaning:'έρχομαι', conj:4,
    act_ind_pres:  ['venio','venis','venit','venimus','venitis','veniunt'],
    act_ind_ipf:   ['veniebam','veniebas','veniebat','veniebamus','veniebatis','veniebant'],
    act_ind_fut:   ['veniam','venies','veniet','veniemus','venietis','venient'],
    act_ind_prf:   ['veni','venisti','venit','venimus','venistis','venerunt'],
    act_ind_plpf:  ['veneram','veneras','venerat','veneramus','veneratis','venerant'],
    act_sub_pres:  ['veniam','venias','veniat','veniamus','veniatis','veniant'],
    act_sub_ipf:   ['venirem','venires','veniret','veniremus','veniretis','venirent'],
    pas_ind_pres:  ['venior','veniris','venitur','venimur','venimini','veniuntur'],
    pas_ind_ipf:   ['veniebar','veniebaris','veniebatur','veniebamur','veniebamini','veniebantur'],
    pas_ind_fut:   ['veniar','venieris','venietur','veniemur','veniemini','venientur'],
    pas_sub_pres:  ['veniar','veniaris','veniatur','veniamur','veniamini','veniantur'],
    pas_sub_ipf:   ['venirer','venireris','veniretur','veniremur','veniremini','venirentur'],
  },
  { inf:'dormire', meaning:'κοιμάμαι', conj:4,
    act_ind_pres:  ['dormio','dormis','dormit','dormimus','dormitis','dormiunt'],
    act_ind_ipf:   ['dormiebam','dormiebas','dormiebat','dormiebamus','dormiebatis','dormiebant'],
    act_ind_fut:   ['dormiam','dormies','dormiet','dormiemus','dormietis','dormient'],
    act_ind_prf:   ['dormivi','dormivisti','dormivit','dormivimus','dormivistis','dormiverunt'],
    act_ind_plpf:  ['dormiveram','dormiveras','dormiverat','dormiveramus','dormiveratis','dormiverant'],
    act_sub_pres:  ['dormiam','dormias','dormiat','dormiamus','dormiatis','dormiant'],
    act_sub_ipf:   ['dormirem','dormires','dormiret','dormiremus','dormiretis','dormirent'],
    pas_ind_pres:  ['dormior','dormiris','dormitur','dormimur','dormimini','dormiuntur'],
    pas_ind_ipf:   ['dormiebar','dormiebaris','dormiebatur','dormiebamur','dormiebamini','dormiebantur'],
    pas_ind_fut:   ['dormiar','dormieris','dormietur','dormiemur','dormiemini','dormientur'],
    pas_sub_pres:  ['dormiar','dormiaris','dormiatur','dormiamur','dormiamini','dormiantur'],
    pas_sub_ipf:   ['dormirer','dormireris','dormiretur','dormiremur','dormiremini','dormirentur'],
  },
];

// Question packs grouped for level selection
const LAT_V_PACKS = [
  { id:'1_ind_act', label:'Α΄ Συζυγία — Οριστική Εν.', conj:[1], keys:['act_ind_pres','act_ind_ipf','act_ind_fut','act_ind_prf','act_ind_plpf'] },
  { id:'1_sub_act', label:'Α΄ Συζυγία — Υποτακτική Εν.', conj:[1], keys:['act_sub_pres','act_sub_ipf'] },
  { id:'1_pas',     label:'Α΄ Συζυγία — Παθητική Φωνή', conj:[1], keys:['pas_ind_pres','pas_ind_ipf','pas_ind_fut','pas_sub_pres','pas_sub_ipf'] },
  { id:'2_ind_act', label:'Β΄ Συζυγία — Οριστική Εν.', conj:[2], keys:['act_ind_pres','act_ind_ipf','act_ind_fut','act_ind_prf','act_ind_plpf'] },
  { id:'2_sub_act', label:'Β΄ Συζυγία — Υποτακτική Εν.', conj:[2], keys:['act_sub_pres','act_sub_ipf'] },
  { id:'2_pas',     label:'Β΄ Συζυγία — Παθητική Φωνή', conj:[2], keys:['pas_ind_pres','pas_ind_ipf','pas_ind_fut','pas_sub_pres','pas_sub_ipf'] },
  { id:'3_ind_act', label:'Γ΄ Συζυγία — Οριστική Εν.', conj:[3], keys:['act_ind_pres','act_ind_ipf','act_ind_fut','act_ind_prf','act_ind_plpf'] },
  { id:'3_sub_act', label:'Γ΄ Συζυγία — Υποτακτική Εν.', conj:[3], keys:['act_sub_pres','act_sub_ipf'] },
  { id:'3_pas',     label:'Γ΄ Συζυγία — Παθητική Φωνή', conj:[3], keys:['pas_ind_pres','pas_ind_ipf','pas_ind_fut','pas_sub_pres','pas_sub_ipf'] },
  { id:'4_ind_act', label:'Δ΄ Συζυγία — Οριστική Εν.', conj:[4], keys:['act_ind_pres','act_ind_ipf','act_ind_fut','act_ind_prf','act_ind_plpf'] },
  { id:'4_sub_act', label:'Δ΄ Συζυγία — Υποτακτική Εν.', conj:[4], keys:['act_sub_pres','act_sub_ipf'] },
  { id:'4_pas',     label:'Δ΄ Συζυγία — Παθητική Φωνή', conj:[4], keys:['pas_ind_pres','pas_ind_ipf','pas_ind_fut','pas_sub_pres','pas_sub_ipf'] },
  { id:'all_pres',  label:'Όλες — Ενεστώτας Οριστικής', conj:[1,2,3,4], keys:['act_ind_pres','pas_ind_pres'] },
  { id:'all_act',   label:'Όλες — Ενεργητική Φωνή',     conj:[1,2,3,4], keys:['act_ind_pres','act_ind_ipf','act_ind_fut','act_ind_prf','act_sub_pres','act_sub_ipf'] },
  { id:'master',    label:'Master — Όλα μαζί',           conj:[1,2,3,4], keys:['act_ind_pres','act_ind_ipf','act_ind_fut','act_ind_prf','act_ind_plpf','act_sub_pres','act_sub_ipf','pas_ind_pres','pas_ind_ipf','pas_ind_fut','pas_sub_pres','pas_sub_ipf'] },
];

function _latvKeyLabel(key) {
  const map = {
    act_ind_pres:'Ενεστ. Οριστ. Εν.', act_ind_ipf:'Παρατ. Οριστ. Εν.', act_ind_fut:'Μελλ. Οριστ. Εν.',
    act_ind_prf:'Παρακ. Οριστ. Εν.', act_ind_plpf:'Υπερσ. Οριστ. Εν.',
    act_sub_pres:'Ενεστ. Υποτ. Εν.', act_sub_ipf:'Παρατ. Υποτ. Εν.',
    pas_ind_pres:'Ενεστ. Οριστ. Παθ.', pas_ind_ipf:'Παρατ. Οριστ. Παθ.', pas_ind_fut:'Μελλ. Οριστ. Παθ.',
    pas_sub_pres:'Ενεστ. Υποτ. Παθ.', pas_sub_ipf:'Παρατ. Υποτ. Παθ.',
  };
  return map[key] || key;
}
