// Latin Noun Declension Data
// Cases: [0]=Nom [1]=Gen [2]=Dat [3]=Acc [4]=Voc [5]=Abl
// s = singular, p = plural

const LAT_N_CASES    = ['Ονομαστική','Γενική','Δοτική','Αιτιατική','Κλητική','Αφαιρετική'];
const LAT_N_CASES_EN = ['Nominative','Genitive','Dative','Accusative','Vocative','Ablative'];

const LAT_N_SUBS = {
  '1f':'Α΄ Κλίση (θηλ.)','1m':'Α΄ Κλίση (αρσ.)',
  '2m':'Β΄ Κλίση (αρσ.)','2m_er':'Β΄ Κλίση -er (αρσ.)','2n':'Β΄ Κλίση (ουδ.)',
  '3cons':'Γ΄ Κλίση (συμφ.)','3istem':'Γ΄ Κλίση (φων.)','3n':'Γ΄ Κλίση (ουδ.)','3n_al':'Γ΄ Κλίση -al/-ar/-e',
  '4m':'Δ΄ Κλίση (αρσ.)','4f':'Δ΄ Κλίση (θηλ.)','4n':'Δ΄ Κλίση (ουδ.)',
  '5m':'Ε΄ Κλίση (αρσ.)','5f':'Ε΄ Κλίση (θηλ.)',
};

const LAT_N_DB = [
  // ═══ Α΄ ΚΛΙΣΗ ═══
  { l:'puella, -ae',    t:'θηλυκό',   d:1, sub:'1f',
    s:['puella','puellae','puellae','puellam','puella','puella'],
    p:['puellae','puellarum','puellis','puellas','puellae','puellis'] },
  { l:'aqua, -ae',      t:'θηλυκό',   d:1, sub:'1f',
    s:['aqua','aquae','aquae','aquam','aqua','aqua'],
    p:['aquae','aquarum','aquis','aquas','aquae','aquis'] },
  { l:'terra, -ae',     t:'θηλυκό',   d:1, sub:'1f',
    s:['terra','terrae','terrae','terram','terra','terra'],
    p:['terrae','terrarum','terris','terras','terrae','terris'] },
  { l:'via, -ae',       t:'θηλυκό',   d:1, sub:'1f',
    s:['via','viae','viae','viam','via','via'],
    p:['viae','viarum','viis','vias','viae','viis'] },
  { l:'silva, -ae',     t:'θηλυκό',   d:1, sub:'1f',
    s:['silva','silvae','silvae','silvam','silva','silva'],
    p:['silvae','silvarum','silvis','silvas','silvae','silvis'] },
  { l:'epistula, -ae',  t:'θηλυκό',   d:1, sub:'1f',
    s:['epistula','epistulae','epistulae','epistulam','epistula','epistula'],
    p:['epistulae','epistularum','epistulis','epistulas','epistulae','epistulis'] },
  { l:'gloria, -ae',    t:'θηλυκό',   d:1, sub:'1f',
    s:['gloria','gloriae','gloriae','gloriam','gloria','gloria'],
    p:['gloriae','gloriarum','gloriis','glorias','gloriae','gloriis'] },
  { l:'luna, -ae',      t:'θηλυκό',   d:1, sub:'1f',
    s:['luna','lunae','lunae','lunam','luna','luna'],
    p:['lunae','lunarum','lunis','lunas','lunae','lunis'] },
  { l:'nauta, -ae',     t:'αρσενικό', d:1, sub:'1m',
    s:['nauta','nautae','nautae','nautam','nauta','nauta'],
    p:['nautae','nautarum','nautis','nautas','nautae','nautis'] },
  { l:'poeta, -ae',     t:'αρσενικό', d:1, sub:'1m',
    s:['poeta','poetae','poetae','poetam','poeta','poeta'],
    p:['poetae','poetarum','poetis','poetas','poetae','poetis'] },
  { l:'agricola, -ae',  t:'αρσενικό', d:1, sub:'1m',
    s:['agricola','agricolae','agricolae','agricolam','agricola','agricola'],
    p:['agricolae','agricolarum','agricolis','agricolas','agricolae','agricolis'] },

  // ═══ Β΄ ΚΛΙΣΗ — αρσ. ═══
  { l:'dominus, -i',    t:'αρσενικό', d:2, sub:'2m',
    s:['dominus','domini','domino','dominum','domine','domino'],
    p:['domini','dominorum','dominis','dominos','domini','dominis'] },
  { l:'amicus, -i',     t:'αρσενικό', d:2, sub:'2m',
    s:['amicus','amici','amico','amicum','amice','amico'],
    p:['amici','amicorum','amicis','amicos','amici','amicis'] },
  { l:'servus, -i',     t:'αρσενικό', d:2, sub:'2m',
    s:['servus','servi','servo','servum','serve','servo'],
    p:['servi','servorum','servis','servos','servi','servis'] },
  { l:'filius, -ii',    t:'αρσενικό', d:2, sub:'2m',
    s:['filius','filii','filio','filium','fili','filio'],
    p:['filii','filiorum','filiis','filios','filii','filiis'] },
  { l:'puer, -i',       t:'αρσενικό', d:2, sub:'2m_er',
    s:['puer','pueri','puero','puerum','puer','puero'],
    p:['pueri','puerorum','pueris','pueros','pueri','pueris'] },
  { l:'magister, -tri', t:'αρσενικό', d:2, sub:'2m_er',
    s:['magister','magistri','magistro','magistrum','magister','magistro'],
    p:['magistri','magistrorum','magistris','magistros','magistri','magistris'] },
  { l:'ager, agri',     t:'αρσενικό', d:2, sub:'2m_er',
    s:['ager','agri','agro','agrum','ager','agro'],
    p:['agri','agrorum','agris','agros','agri','agris'] },
  // Β΄ ΚΛΙΣΗ — ουδ.
  { l:'donum, -i',      t:'ουδέτερο', d:2, sub:'2n',
    s:['donum','doni','dono','donum','donum','dono'],
    p:['dona','donorum','donis','dona','dona','donis'] },
  { l:'bellum, -i',     t:'ουδέτερο', d:2, sub:'2n',
    s:['bellum','belli','bello','bellum','bellum','bello'],
    p:['bella','bellorum','bellis','bella','bella','bellis'] },
  { l:'regnum, -i',     t:'ουδέτερο', d:2, sub:'2n',
    s:['regnum','regni','regno','regnum','regnum','regno'],
    p:['regna','regnorum','regnis','regna','regna','regnis'] },
  { l:'templum, -i',    t:'ουδέτερο', d:2, sub:'2n',
    s:['templum','templi','templo','templum','templum','templo'],
    p:['templa','templorum','templis','templa','templa','templis'] },
  { l:'verbum, -i',     t:'ουδέτερο', d:2, sub:'2n',
    s:['verbum','verbi','verbo','verbum','verbum','verbo'],
    p:['verba','verborum','verbis','verba','verba','verbis'] },
  { l:'oppidum, -i',    t:'ουδέτερο', d:2, sub:'2n',
    s:['oppidum','oppidi','oppido','oppidum','oppidum','oppido'],
    p:['oppida','oppidorum','oppidis','oppida','oppida','oppidis'] },

  // ═══ Γ΄ ΚΛΙΣΗ — συμφ. ═══
  { l:'rex, regis',      t:'αρσενικό', d:3, sub:'3cons',
    s:['rex','regis','regi','regem','rex','rege'],
    p:['reges','regum','regibus','reges','reges','regibus'] },
  { l:'miles, militis',  t:'αρσενικό', d:3, sub:'3cons',
    s:['miles','militis','militi','militem','miles','milite'],
    p:['milites','militum','militibus','milites','milites','militibus'] },
  { l:'homo, hominis',   t:'αρσενικό', d:3, sub:'3cons',
    s:['homo','hominis','homini','hominem','homo','homine'],
    p:['homines','hominum','hominibus','homines','homines','hominibus'] },
  { l:'pater, patris',   t:'αρσενικό', d:3, sub:'3cons',
    s:['pater','patris','patri','patrem','pater','patre'],
    p:['patres','patrum','patribus','patres','patres','patribus'] },
  { l:'mater, matris',   t:'θηλυκό',  d:3, sub:'3cons',
    s:['mater','matris','matri','matrem','mater','matre'],
    p:['matres','matrum','matribus','matres','matres','matribus'] },
  { l:'vox, vocis',      t:'θηλυκό',  d:3, sub:'3cons',
    s:['vox','vocis','voci','vocem','vox','voce'],
    p:['voces','vocum','vocibus','voces','voces','vocibus'] },
  { l:'lex, legis',      t:'θηλυκό',  d:3, sub:'3cons',
    s:['lex','legis','legi','legem','lex','lege'],
    p:['leges','legum','legibus','leges','leges','legibus'] },
  { l:'caput, capitis',  t:'ουδέτερο', d:3, sub:'3cons',
    s:['caput','capitis','capiti','caput','caput','capite'],
    p:['capita','capitum','capitibus','capita','capita','capitibus'] },
  // Γ΄ ΚΛΙΣΗ — φωνηεντόληκτα i-stems
  { l:'civis, civis',    t:'αρσενικό', d:3, sub:'3istem',
    s:['civis','civis','civi','civem','civis','cive'],
    p:['cives','civium','civibus','cives','cives','civibus'] },
  { l:'hostis, hostis',  t:'αρσενικό', d:3, sub:'3istem',
    s:['hostis','hostis','hosti','hostem','hostis','hoste'],
    p:['hostes','hostium','hostibus','hostes','hostes','hostibus'] },
  { l:'urbs, urbis',     t:'θηλυκό',  d:3, sub:'3istem',
    s:['urbs','urbis','urbi','urbem','urbs','urbe'],
    p:['urbes','urbium','urbibus','urbes','urbes','urbibus'] },
  { l:'mons, montis',    t:'αρσενικό', d:3, sub:'3istem',
    s:['mons','montis','monti','montem','mons','monte'],
    p:['montes','montium','montibus','montes','montes','montibus'] },
  // Γ΄ ΚΛΙΣΗ — ουδ.
  { l:'nomen, nominis',  t:'ουδέτερο', d:3, sub:'3n',
    s:['nomen','nominis','nomini','nomen','nomen','nomine'],
    p:['nomina','nominum','nominibus','nomina','nomina','nominibus'] },
  { l:'corpus, corporis',t:'ουδέτερο', d:3, sub:'3n',
    s:['corpus','corporis','corpori','corpus','corpus','corpore'],
    p:['corpora','corporum','corporibus','corpora','corpora','corporibus'] },
  { l:'tempus, temporis',t:'ουδέτερο', d:3, sub:'3n',
    s:['tempus','temporis','tempori','tempus','tempus','tempore'],
    p:['tempora','temporum','temporibus','tempora','tempora','temporibus'] },
  { l:'opus, operis',    t:'ουδέτερο', d:3, sub:'3n',
    s:['opus','operis','operi','opus','opus','opere'],
    p:['opera','operum','operibus','opera','opera','operibus'] },
  // Γ΄ ΚΛΙΣΗ — ουδ. -al/-ar/-e
  { l:'animal, animalis',t:'ουδέτερο', d:3, sub:'3n_al',
    s:['animal','animalis','animali','animal','animal','animali'],
    p:['animalia','animalium','animalibus','animalia','animalia','animalibus'] },
  { l:'mare, maris',     t:'ουδέτερο', d:3, sub:'3n_al',
    s:['mare','maris','mari','mare','mare','mari'],
    p:['maria','marium','maribus','maria','maria','maribus'] },
  { l:'exemplar, exemplaris',t:'ουδέτερο',d:3,sub:'3n_al',
    s:['exemplar','exemplaris','exemplari','exemplar','exemplar','exemplari'],
    p:['exemplaria','exemplarium','exemplaribus','exemplaria','exemplaria','exemplaribus'] },

  // ═══ Δ΄ ΚΛΙΣΗ ═══
  { l:'manus, -us',      t:'θηλυκό',  d:4, sub:'4f',
    s:['manus','manus','manui','manum','manus','manu'],
    p:['manus','manuum','manibus','manus','manus','manibus'] },
  { l:'exercitus, -us',  t:'αρσενικό',d:4, sub:'4m',
    s:['exercitus','exercitus','exercitui','exercitum','exercitus','exercitu'],
    p:['exercitus','exercituum','exercitibus','exercitus','exercitus','exercitibus'] },
  { l:'portus, -us',     t:'αρσενικό',d:4, sub:'4m',
    s:['portus','portus','portui','portum','portus','portu'],
    p:['portus','portuum','portibus','portus','portus','portibus'] },
  { l:'fructus, -us',    t:'αρσενικό',d:4, sub:'4m',
    s:['fructus','fructus','fructui','fructum','fructus','fructu'],
    p:['fructus','fructuum','fructibus','fructus','fructus','fructibus'] },
  { l:'cornu, -us',      t:'ουδέτερο',d:4, sub:'4n',
    s:['cornu','cornus','cornu','cornu','cornu','cornu'],
    p:['cornua','cornuum','cornibus','cornua','cornua','cornibus'] },
  { l:'genu, -us',       t:'ουδέτερο',d:4, sub:'4n',
    s:['genu','genus','genu','genu','genu','genu'],
    p:['genua','genuum','genibus','genua','genua','genibus'] },

  // ═══ Ε΄ ΚΛΙΣΗ ═══
  { l:'dies, -ei',       t:'αρσενικό',d:5, sub:'5m',
    s:['dies','diei','diei','diem','dies','die'],
    p:['dies','dierum','diebus','dies','dies','diebus'] },
  { l:'res, -ei',        t:'θηλυκό',  d:5, sub:'5f',
    s:['res','rei','rei','rem','res','re'],
    p:['res','rerum','rebus','res','res','rebus'] },
  { l:'spes, -ei',       t:'θηλυκό',  d:5, sub:'5f',
    s:['spes','spei','spei','spem','spes','spe'],
    p:['spes','-','-','spes','spes','-'] },
  { l:'fides, -ei',      t:'θηλυκό',  d:5, sub:'5f',
    s:['fides','fidei','fidei','fidem','fides','fide'],
    p:['-','-','-','-','-','-'] },
  { l:'acies, -ei',      t:'θηλυκό',  d:5, sub:'5f',
    s:['acies','aciei','aciei','aciem','acies','acie'],
    p:['acies','-','-','acies','acies','-'] },
];
