'use strict';

const LAT_KATA_FIELDS = [
  { key:'pres', label:'Ενεστώτας'    },
  { key:'perf', label:'Παρακείμενος' },
  { key:'sup',  label:'Σούπινο'      },
  { key:'inf',  label:'Απαρέμφατο'   },
];

// 339 Latin verbs — principal parts + texts where they appear (16-50)
// '-' = form does not exist   'passim' = texts array for sum (all texts)
const LAT_KATA_DB = [
  // ── Α ──
  {n:1,  pres:'abdo',             perf:'abdidi',          sup:'abditum',         inf:'abdĕre',              meaning:'κρύβω',                      texts:[17,20]},
  {n:2,  pres:'abeo',             perf:'abi(v)i',          sup:'abitum',          inf:'abīre',               meaning:'φεύγω',                      texts:[21,28,31]},
  {n:3,  pres:'abicio',           perf:'abieci',           sup:'abiectum',        inf:'abicĕre',             meaning:'καταθέτω',                   texts:[34,45]},
  {n:4,  pres:'abstineo',         perf:'abstinui',         sup:'abstentum',       inf:'abstinēre',           meaning:'απέχω',                      texts:[31]},
  {n:5,  pres:'absum',            perf:'afui',             sup:'-',               inf:'abesse',              meaning:'απουσιάζω, απέχω',            texts:[18,21,35]},
  {n:6,  pres:'accedo',           perf:'accessi',          sup:'accessum',        inf:'accedĕre',            meaning:'πλησιάζω',                   texts:[32]},
  {n:7,  pres:'accido',           perf:'accidi',           sup:'-',               inf:'accidĕre',            meaning:'πέφτω κάτω',                 texts:[22]},
  {n:8,  pres:'accipio',          perf:'accepi',           sup:'acceptum',        inf:'accipĕre',            meaning:'μαθαίνω',                    texts:[21,24,35,39]},
  {n:9,  pres:'adduco',           perf:'adduxi',           sup:'adductum',        inf:'adducĕre',            meaning:'οδηγώ',                      texts:[17,18,20]},
  {n:10, pres:'adeo',             perf:'adi(v)i',          sup:'aditum',          inf:'adīre',               meaning:'πλησιάζω',                   texts:[45]},
  {n:11, pres:'adfero',           perf:'attuli',           sup:'allatum',         inf:'adferre',             meaning:'φέρνω',                      texts:[25,29,36]},
  {n:12, pres:'adficio',          perf:'adfeci',           sup:'adfectum',        inf:'adficĕre',            meaning:'περιβάλλω',                  texts:[28]},
  {n:13, pres:'adgnosco',         perf:'adgnovi',          sup:'adgnitum',        inf:'adgnoscĕre',          meaning:'αναγνωρίζω',                 texts:[20]},
  {n:14, pres:'adhaeresco',       perf:'adhaesi',          sup:'adhaesum',        inf:'adhaerescĕre',        meaning:'προσκολλιέμαι',              texts:[45]},
  {n:15, pres:'adhortor',         perf:'adhortatus sum',   sup:'-',               inf:'adhortari',           meaning:'προτρέπω',                   texts:[45]},
  {n:16, pres:'adligo',           perf:'adligavi',         sup:'adligatum',       inf:'adligāre',            meaning:'δένω',                       texts:[45]},
  {n:17, pres:'administro',       perf:'administravi',     sup:'administratum',   inf:'administrāre',        meaning:'διαχειρίζομαι',              texts:[32]},
  {n:18, pres:'admiror',          perf:'admiratus sum',    sup:'-',               inf:'admirari',            meaning:'θαυμάζω',                    texts:[34]},
  {n:19, pres:'admitto',          perf:'admisi',           sup:'admissum',        inf:'admittĕre',           meaning:'δέχομαι',                    texts:[48]},
  {n:20, pres:'adsum',            perf:'affui',            sup:'-',               inf:'adesse',              meaning:'είμαι παρών',                texts:[45]},
  {n:21, pres:'aegroto',          perf:'aegrotavi',        sup:'aegrotatum',      inf:'aegrotāre',           meaning:'είμαι άρρωστος',             texts:[23]},
  {n:22, pres:'ago',              perf:'egi',              sup:'actum',           inf:'agĕre',               meaning:'κάνω, οδηγώ',                texts:[23,39]},
  {n:23, pres:'aio',              perf:'-',                sup:'-',               inf:'-',                   meaning:'λέγω',                       texts:[27]},
  {n:24, pres:'alo',              perf:'alui',             sup:'al(i)tum',        inf:'alĕre',               meaning:'εκτρέφω',                    texts:[42,43]},
  {n:25, pres:'amo',              perf:'amavi',            sup:'amatum',          inf:'amāre',               meaning:'αγαπώ',                      texts:[22,38]},
  {n:26, pres:'amoveo',           perf:'amovi',            sup:'amotum',          inf:'amovēre',             meaning:'απομακρύνω',                 texts:[18]},
  {n:27, pres:'animadverto',      perf:'animadverti',      sup:'animadversum',    inf:'animadvertĕre',       meaning:'παρατηρώ / τιμωρώ',          texts:[20,34,42]},
  {n:28, pres:'antecello',        perf:'-',                sup:'-',               inf:'antecellĕre',         meaning:'ξεπερνώ',                    texts:[31]},
  {n:29, pres:'antepono',         perf:'anteposui',        sup:'antepositum',     inf:'anteponĕre',          meaning:'προκρίνω',                   texts:[46]},
  {n:30, pres:'appendo',          perf:'appendi',          sup:'appensum',        inf:'appendĕre',           meaning:'ζυγίζω',                     texts:[21]},
  {n:31, pres:'appropinquo',      perf:'appropinquavi',    sup:'appropinquatum',  inf:'appropinquāre',       meaning:'πλησιάζω',                   texts:[16,34]},
  {n:32, pres:'arbitror',         perf:'arbitratus sum',   sup:'-',               inf:'arbitrari',           meaning:'νομίζω, πιστεύω',            texts:[22]},
  {n:33, pres:'armo',             perf:'armavi',           sup:'armatum',         inf:'armāre',              meaning:'οπλίζω',                     texts:[33]},
  {n:34, pres:'ascendo',          perf:'ascendi',          sup:'ascensum',        inf:'ascendĕre',           meaning:'ανεβαίνω',                   texts:[23]},
  {n:35, pres:'aspicio',          perf:'aspexi',           sup:'aspectum',        inf:'aspicĕre',            meaning:'κοιτάζω',                    texts:[18]},
  {n:36, pres:'assideo',          perf:'assedi',           sup:'assessum',        inf:'assidēre',            meaning:'κάθομαι δίπλα',              texts:[36]},
  {n:37, pres:'audeo',            perf:'ausus sum',        sup:'-',               inf:'audēre',              meaning:'τολμώ',                      texts:[40]},
  {n:38, pres:'audio',            perf:'audivi',           sup:'auditum',         inf:'audīre',              meaning:'ακούω',                      texts:[18,29,34,38,47]},
  {n:39, pres:'(aveo)',           perf:'-',                sup:'-',               inf:'avēre',               meaning:'χαίρε!',                     texts:[29]},
  {n:40, pres:'averto',           perf:'averti',           sup:'aversum',         inf:'avertĕre',            meaning:'βγάζω από το δρόμο',         texts:[39]},
  // ── C ──
  {n:41, pres:'cado',             perf:'cecidi',           sup:'casum',           inf:'cadĕre',              meaning:'πέφτω',                      texts:[43,44,46]},
  {n:42, pres:'capio',            perf:'cepi',             sup:'captum',          inf:'capĕre',              meaning:'πιάνω, συλλαμβάνω',          texts:[16,20,34]},
  {n:43, pres:'caveo',            perf:'cavi',             sup:'cautum',          inf:'cavēre',              meaning:'προσέχω, φυλάγομαι',         texts:[25]},
  {n:44, pres:'cedo',             perf:'cessi',            sup:'cessum',          inf:'cedĕre',              meaning:'παραχωρώ',                   texts:[38,49]},
  {n:45, pres:'ceno',             perf:'cenavi',           sup:'cenatum',         inf:'cenāre',              meaning:'δειπνώ',                     texts:[36]},
  {n:46, pres:'censeo',           perf:'censui',           sup:'censum',          inf:'censēre',             meaning:'πιστεύω, νομίζω',            texts:[46]},
  {n:47, pres:'cerno',            perf:'crevi',            sup:'cretum',          inf:'cernĕre',             meaning:'διακρίνω, κρίνω',            texts:[16,31]},
  {n:48, pres:'circumsedeo',      perf:'circumsedi',       sup:'circumsessum',    inf:'circumsedēre',        meaning:'περικυκλώνω',                texts:[40]},
  {n:49, pres:'clamo',            perf:'clamavi',          sup:'clamatum',        inf:'clamāre',             meaning:'φωνάζω',                     texts:[37]},
  {n:50, pres:'coepi',            perf:'-',                sup:'-',               inf:'coepisse',            meaning:'αρχίζω',                     texts:[18,47]},
  {n:51, pres:'cogito',           perf:'cogitavi',         sup:'cogitatum',       inf:'cogitāre',            meaning:'σκέπτομαι',                  texts:[32]},
  {n:52, pres:'cognosco',         perf:'cognovi',          sup:'cognitum',        inf:'cognoscĕre',          meaning:'γνωρίζω',                    texts:[24,28,45,49]},
  {n:53, pres:'cogo',             perf:'coegi',            sup:'coactum',         inf:'cogĕre',              meaning:'συγκαλώ, εξαναγκάζω',        texts:[37,40]},
  {n:54, pres:'cohibeo',          perf:'cohibui',          sup:'cohibitum',       inf:'cohibēre',            meaning:'συγκρατώ',                   texts:[23]},
  {n:55, pres:'colo',             perf:'colui',            sup:'cultum',          inf:'colĕre',              meaning:'καλλιεργώ / λατρεύω',        texts:[32,41,44]},
  {n:56, pres:'complector',       perf:'complexus sum',    sup:'-',               inf:'complecti',           meaning:'αγκαλιάζω',                  texts:[26]},
  {n:57, pres:'comprehendo',      perf:'comprehendi',      sup:'comprehensum',    inf:'comprehendĕre',       meaning:'συλλαμβάνω',                 texts:[16,28]},
  {n:58, pres:'comprimo',         perf:'compressi',        sup:'compressum',      inf:'comprimĕre',          meaning:'περιορίζω',                  texts:[33]},
  {n:59, pres:'condo',            perf:'condidi',          sup:'conditum',        inf:'condĕre',             meaning:'κτίζω',                      texts:[18]},
  {n:60, pres:'conduco',          perf:'conduxi',          sup:'conductum',       inf:'conducĕre',           meaning:'νοικιάζω',                   texts:[23]},
  {n:61, pres:'confero',          perf:'contuli',          sup:'collatum',        inf:'conferre',            meaning:'συγκεντρώνω',                texts:[35]},
  {n:62, pres:'confido',          perf:'confisus sum',     sup:'-',               inf:'confidĕre',           meaning:'εμπιστεύομαι',               texts:[25,31]},
  {n:63, pres:'confirmo',         perf:'confirmavi',       sup:'confirmatum',     inf:'confirmāre',          meaning:'επιβεβαιώνω',                texts:[38,42]},
  {n:64, pres:'conformo',         perf:'conformavi',       sup:'conformatum',     inf:'conformāre',          meaning:'διαμορφώνω',                 texts:[32]},
  {n:65, pres:'confundo',         perf:'confudi',          sup:'confusum',        inf:'confundĕre',          meaning:'συγχέω',                     texts:[18]},
  {n:66, pres:'congredior',       perf:'congressus sum',   sup:'-',               inf:'congredi',            meaning:'συγκρούομαι',                texts:[31]},
  {n:67, pres:'congruo',          perf:'congrui',          sup:'-',               inf:'congruĕre',           meaning:'συμφωνώ',                    texts:[38]},
  {n:68, pres:'coniuro',          perf:'coniuravi',        sup:'coniuratum',      inf:'coniurāre',           meaning:'συνομωτώ',                   texts:[19]},
  {n:69, pres:'conloco',          perf:'conlocavi',        sup:'conlocatum',      inf:'conlocāre',           meaning:'εγκαθιστώ',                  texts:[34]},
  {n:70, pres:'conloquor',        perf:'conlocutus sum',   sup:'-',               inf:'conloqui',            meaning:'συζητώ',                     texts:[48]},
  {n:71, pres:'conor',            perf:'conatus sum',      sup:'-',               inf:'conari',              meaning:'προσπαθώ',                   texts:[18]},
  {n:72, pres:'conscribo',        perf:'conscripsi',       sup:'conscriptum',     inf:'conscribĕre',         meaning:'γράφω',                      texts:[45,50]},
  {n:73, pres:'consecro',         perf:'consecravi',       sup:'consecratum',     inf:'consecrāre',          meaning:'αφιερώνω',                   texts:[34]},
  {n:74, pres:'consequor',        perf:'consecutus sum',   sup:'-',               inf:'consequi',            meaning:'ακολουθώ, πετυχαίνω',        texts:[19,41,46]},
  {n:75, pres:'conservo',         perf:'conservavi',       sup:'conservatum',     inf:'conservāre',          meaning:'σώζω',                       texts:[40]},
  {n:76, pres:'consido',          perf:'consedi',          sup:'consessum',       inf:'considĕre',           meaning:'κάθομαι',                    texts:[16]},
  {n:77, pres:'conspicio',        perf:'conspexi',         sup:'conspectum',      inf:'conspicĕre',          meaning:'βλέπω',                      texts:[45]},
  {n:78, pres:'constituo',        perf:'constitui',        sup:'constitutum',     inf:'constituĕre',         meaning:'αποφασίζω',                  texts:[30,33,45]},
  {n:79, pres:'consulo',          perf:'consului',         sup:'consultum',       inf:'consulĕre',           meaning:'φροντίζω',                   texts:[22,25,46]},
  {n:80, pres:'contemno',         perf:'contempsi',        sup:'contemptum',      inf:'contemnĕre',          meaning:'περιφρονώ',                  texts:[36]},
  {n:81, pres:'contendo',         perf:'contendi',         sup:'contentum',       inf:'contendĕre',          meaning:'φιλονικώ',                   texts:[50]},
  {n:82, pres:'converto',         perf:'converti',         sup:'conversum',       inf:'convertĕre',          meaning:'γυρίζω',                     texts:[18]},
  {n:83, pres:'corrumpo',         perf:'corrupi',          sup:'corruptum',       inf:'corrumpĕre',          meaning:'διαφθείρω',                  texts:[36]},
  {n:84, pres:'credo',            perf:'credidi',          sup:'creditum',        inf:'credĕre',             meaning:'πιστεύω',                    texts:[24,25,42,48]},
  {n:85, pres:'cupio',            perf:'cupivi',           sup:'cupitum',         inf:'cupĕre',              meaning:'επιθυμώ',                    texts:[17,37]},
  {n:86, pres:'curo',             perf:'curavi',           sup:'curatum',         inf:'curāre',              meaning:'φροντίζω',                   texts:[35,45]},
  // ── D ──
  {n:87,  pres:'debeo',           perf:'debui',            sup:'debitum',         inf:'debēre',              meaning:'οφείλω, πρέπει',             texts:[30]},
  {n:88,  pres:'decerpo',         perf:'decerpsi',         sup:'decerptum',       inf:'decerpĕre',           meaning:'κόβω',                       texts:[25]},
  {n:89,  pres:'decet',           perf:'decuit',           sup:'-',               inf:'decēre',              meaning:'αρμόζει',                    texts:[46]},
  {n:90,  pres:'dedo',            perf:'dedidi',           sup:'deditum',         inf:'dedĕre',              meaning:'παραδίδω',                   texts:[16]},
  {n:91,  pres:'deduco',          perf:'deduxi',           sup:'deductum',        inf:'deducĕre',            meaning:'οδηγώ, φέρνω',               texts:[28,37]},
  {n:92,  pres:'defero',          perf:'detuli',           sup:'delatum',         inf:'deferre',             meaning:'μεταφέρω',                   texts:[20,45]},
  {n:93,  pres:'deleo',           perf:'delevi',           sup:'deletum',         inf:'delēre',              meaning:'καταστρέφω',                 texts:[21,25]},
  {n:94,  pres:'depono',          perf:'deposui',          sup:'depositum',       inf:'deponĕre',            meaning:'καταθέτω',                   texts:[25]},
  {n:95,  pres:'deprehendo',      perf:'deprehendi',       sup:'deprehensum',     inf:'deprehendĕre',        meaning:'συλλαμβάνω, ανακαλύπτω',     texts:[19,47]},
  {n:96,  pres:'desero',          perf:'deserui',          sup:'desertum',        inf:'deserĕre',            meaning:'εγκαταλείπω',                texts:[35]},
  {n:97,  pres:'desidero',        perf:'desideravi',       sup:'desideratum',     inf:'desiderāre',          meaning:'επιθυμώ',                    texts:[27]},
  {n:98,  pres:'desisto',         perf:'destiti',          sup:'-',               inf:'desistĕre',           meaning:'σταματώ',                    texts:[37]},
  {n:99,  pres:'deterreo',        perf:'deterrui',         sup:'deterritum',      inf:'deterrēre',           meaning:'αποθαρρύνω',                 texts:[47]},
  {n:100, pres:'deverto',         perf:'deverti',          sup:'deversum',        inf:'devertĕre',           meaning:'καταλύω',                    texts:[27]},
  {n:101, pres:'dico',            perf:'dixi',             sup:'dictum',          inf:'dicĕre',              meaning:'λέγω',                       texts:[18,21,24,25,26,27,29,36,37,38,40,41,42,44,48,50]},
  {n:102, pres:'diffluo',         perf:'diffluxi',         sup:'diffluctum',      inf:'diffluĕre',           meaning:'διαρρέω',                    texts:[33]},
  {n:103, pres:'dilabor',         perf:'dilapsus sum',     sup:'-',               inf:'dilabi',              meaning:'καταρρέω',                   texts:[33]},
  {n:104, pres:'diligo',          perf:'dilexi',           sup:'dilectum',        inf:'diligĕre',            meaning:'αγαπώ',                      texts:[26,44]},
  {n:105, pres:'discedo',         perf:'discessi',         sup:'discessum',       inf:'discedĕre',           meaning:'αποχωρώ',                    texts:[16,17,35]},
  {n:106, pres:'disco',           perf:'didici',           sup:'-',               inf:'discĕre',             meaning:'μαθαίνω',                    texts:[29]},
  {n:107, pres:'discurro',        perf:'discurri',         sup:'discursum',       inf:'discurrĕre',          meaning:'τρέχω',                      texts:[20]},
  {n:108, pres:'dissentio',       perf:'dissensi',         sup:'dissensum',       inf:'dissentīre',          meaning:'διαφωνώ',                    texts:[50]},
  {n:109, pres:'dissimulo',       perf:'dissimulavi',      sup:'dissimulatum',    inf:'dissimulāre',         meaning:'προσποιούμαι',               texts:[42,47]},
  {n:110, pres:'divido',          perf:'divisi',           sup:'divisum',         inf:'dividĕre',            meaning:'μοιράζω',                    texts:[21]},
  {n:111, pres:'do',              perf:'dedi',             sup:'datum',           inf:'dāre',                meaning:'δίνω',                       texts:[21,23,48]},
  {n:112, pres:'doceo',           perf:'docui',            sup:'doctum',          inf:'docēre',              meaning:'διδάσκω, δείχνω',            texts:[29,48]},
  {n:113, pres:'dormio',          perf:'dormivi',          sup:'dormitum',        inf:'dormīre',             meaning:'κοιμάμαι',                   texts:[18]},
  {n:114, pres:'dubito',          perf:'dubitavi',         sup:'dubitatum',       inf:'dubitāre',            meaning:'αμφιβάλλω',                  texts:[47]},
  {n:115, pres:'duco',            perf:'duxi',             sup:'ductum',          inf:'ducĕre',              meaning:'οδηγώ / θεωρώ',              texts:[32,38]},
  // ── E ──
  {n:116, pres:'edico',           perf:'edixi',            sup:'edictum',         inf:'edicĕre',             meaning:'διατάζω',                    texts:[31]},
  {n:117, pres:'efficio',         perf:'effeci',           sup:'effectum',        inf:'efficĕre',            meaning:'κατορθώνω',                  texts:[39]},
  {n:118, pres:'egredior',        perf:'egressus sum',     sup:'-',               inf:'egredi',              meaning:'βγαίνω',                     texts:[23]},
  {n:119, pres:'elabor',          perf:'elapsus sum',      sup:'-',               inf:'elabi',               meaning:'ξεγλιστρώ',                  texts:[49]},
  {n:120, pres:'emitto',          perf:'emisi',            sup:'emissum',         inf:'emittĕre',            meaning:'αφήνω ελεύθερο',             texts:[48]},
  {n:121, pres:'emo',             perf:'emi',              sup:'emptum',          inf:'emĕre',               meaning:'αγοράζω',                    texts:[29]},
  {n:122, pres:'eo',              perf:'ivi',              sup:'itum',            inf:'īre',                 meaning:'πηγαίνω',                    texts:[40]},
  {n:123, pres:'everto',          perf:'everti',           sup:'eversum',         inf:'evertĕre',            meaning:'καταστρέφω εντελώς',         texts:[21]},
  {n:124, pres:'excito',          perf:'excitavi',         sup:'excitatum',       inf:'excitāre',            meaning:'αποκαθιστώ',                 texts:[18,33]},
  {n:125, pres:'exclamo',         perf:'exclamavi',        sup:'exclamatum',      inf:'exclamāre',           meaning:'αναφωνώ',                    texts:[24]},
  {n:126, pres:'excludo',         perf:'exclusi',          sup:'exclusum',        inf:'excludĕre',           meaning:'διώχνω',                     texts:[20]},
  {n:127, pres:'exigo',           perf:'exegi',            sup:'exactum',         inf:'exigĕre',             meaning:'εισπράττω',                  texts:[35]},
  {n:128, pres:'existimo',        perf:'existimavi',       sup:'existimatum',     inf:'existimāre',          meaning:'νομίζω',                     texts:[34]},
  {n:129, pres:'expecto',         perf:'expectavi',        sup:'expectatum',      inf:'expectāre',           meaning:'περιμένω',                   texts:[38]},
  {n:130, pres:'expello',         perf:'expuli',           sup:'expulsum',        inf:'expellĕre',           meaning:'διώχνω',                     texts:[19]},
  {n:131, pres:'experior',        perf:'expertus sum',     sup:'-',               inf:'experīri',            meaning:'δοκιμάζω',                   texts:[49]},
  {n:132, pres:'expeto',          perf:'expeti(v)i',       sup:'expetitum',       inf:'expetĕre',            meaning:'επιδιώκω',                   texts:[32]},
  {n:133, pres:'explico',         perf:'explicavi',        sup:'explicatum',      inf:'explicāre',           meaning:'εκφράζω',                    texts:[39]},
  {n:134, pres:'ex(s)ulo',        perf:'ex(s)ulavi',       sup:'ex(s)ulatum',     inf:'ex(s)ulāre',          meaning:'είμαι εξόριστος',            texts:[44]},
  {n:135, pres:'exterreo',        perf:'exterrui',         sup:'exterritum',      inf:'exterrēre',           meaning:'τρομοκρατώ',                 texts:[20]},
  {n:136, pres:'extraho',         perf:'extraxi',          sup:'extractum',       inf:'extrahĕre',           meaning:'τραβάω, παρατείνω',          texts:[20,47]},
  // ── F ──
  {n:137, pres:'facio',           perf:'feci',             sup:'factum',          inf:'facĕre',              meaning:'κάνω',                       texts:[24,33,37,38,39,47,48]},
  {n:138, pres:'fateor',          perf:'fassus sum',       sup:'-',               inf:'fatēri',              meaning:'ομολογώ',                    texts:[42]},
  {n:139, pres:'fatiscor',        perf:'-',                sup:'-',               inf:'fatisci',             meaning:'κουράζομαι',                 texts:[18]},
  {n:140, pres:'fero',            perf:'tuli',             sup:'latum',           inf:'ferre',               meaning:'φέρνω, υπομένω',             texts:[22,26,44]},
  {n:141, pres:'fingo',           perf:'finxi',            sup:'fictum',          inf:'fingĕre',             meaning:'πλάθω',                      texts:[17]},
  {n:142, pres:'fio',             perf:'factus sum',       sup:'-',               inf:'fieri',               meaning:'γίνομαι',                    texts:[16,20,21,27,33,36,37,39,42,44,46]},
  {n:143, pres:'fugio',           perf:'fugi',             sup:'fugitum',         inf:'fugĕre',              meaning:'φεύγω',                      texts:[16,28,41,48]},
  {n:144, pres:'fugo',            perf:'fugavi',           sup:'fugatum',         inf:'fugāre',              meaning:'τρέπω σε φυγή',              texts:[31]},
  {n:145, pres:'fundo',           perf:'fudi',             sup:'fusum',           inf:'fundĕre',             meaning:'χύνω / τρέπω σε φυγή',       texts:[35]},
  {n:146, pres:'funero',          perf:'funeravi',         sup:'funeratum',       inf:'funerāre',            meaning:'κηδεύω',                     texts:[35]},
  // ── G ──
  {n:147, pres:'gero',            perf:'gessi',            sup:'gestum',          inf:'gerĕre',              meaning:'διεξάγω / διοικώ',           texts:[16,32,45]},
  {n:148, pres:'gigno',           perf:'genui',            sup:'genitum',         inf:'gignĕre',             meaning:'γεννώ',                      texts:[27,43]},
  // ── H ──
  {n:149, pres:'habeo',           perf:'habui',            sup:'habitum',         inf:'habēre',              meaning:'έχω',                        texts:[17,25,30,41,43,44,47,50]},
  // ── I ──
  {n:150, pres:'iaceo',           perf:'iacui',            sup:'iacitum',         inf:'iacēre',              meaning:'κείμαι, βρίσκομαι',          texts:[32,33]},
  {n:151, pres:'ignoro',          perf:'ignoravi',         sup:'ignoratum',       inf:'ignorāre',            meaning:'αγνοώ',                      texts:[23]},
  {n:152, pres:'imitor',          perf:'imitatus sum',     sup:'-',               inf:'imitāri',             meaning:'μιμούμαι',                   texts:[22,32]},
  {n:153, pres:'immineo',         perf:'-',                sup:'-',               inf:'imminēre',            meaning:'πλησιάζω απειλητικά',        texts:[42]},
  {n:154, pres:'impendo',         perf:'impendi',          sup:'impensum',        inf:'impendĕre',           meaning:'ξοδεύω',                     texts:[29]},
  {n:155, pres:'impero',          perf:'imperavi',         sup:'imperatum',       inf:'imperāre',            meaning:'διατάζω',                    texts:[36,48]},
  {n:156, pres:'impetro',         perf:'impetravi',        sup:'impetratum',      inf:'impetrāre',           meaning:'κατορθώνω',                  texts:[23]},
  {n:157, pres:'impleo',          perf:'implevi',          sup:'impletum',        inf:'implēre',             meaning:'συμπληρώνω',                 texts:[26]},
  {n:158, pres:'impono',          perf:'imposui',          sup:'impositum',       inf:'imponĕre',            meaning:'επιβάλλω / επιβιβάζω',       texts:[23]},
  {n:159, pres:'incito',          perf:'incitavi',         sup:'incitatum',       inf:'incitāre',            meaning:'παρακινώ',                   texts:[29]},
  {n:160, pres:'indignor',        perf:'indignatus sum',   sup:'-',               inf:'indignari',           meaning:'αγανακτώ',                   texts:[24]},
  {n:161, pres:'induco',          perf:'induxi',           sup:'inductum',        inf:'inducĕre',            meaning:'εισάγω',                     texts:[47]},
  {n:162, pres:'ingredior',       perf:'ingressus sum',    sup:'-',               inf:'ingredi',             meaning:'εισέρχομαι',                 texts:[43]},
  {n:163, pres:'inhaereo',        perf:'inhaesi',          sup:'inhaesum',        inf:'inhaerēre',           meaning:'προσκολλιέμαι',              texts:[26]},
  {n:164, pres:'inquam',          perf:'-',                sup:'-',               inf:'-',                   meaning:'λέγω',                       texts:[24,25,27,49]},
  {n:165, pres:'instinguo',       perf:'instinxi',         sup:'instinctum',      inf:'instinguĕre',         meaning:'κατευθύνω',                  texts:[48]},
  {n:166, pres:'instituo',        perf:'institui',         sup:'institutum',      inf:'instituĕre',          meaning:'διδάσκω',                    texts:[29]},
  {n:167, pres:'insto',           perf:'institi',          sup:'-',               inf:'instāre',             meaning:'ασκώ πίεση',                 texts:[40]},
  {n:168, pres:'intellego',       perf:'intellexi',        sup:'intellectum',     inf:'intellegĕre',         meaning:'καταλαβαίνω',                texts:[41,42,44]},
  {n:169, pres:'intendo',         perf:'intendi',          sup:'intentum',        inf:'intendĕre',           meaning:'κατευθύνομαι',               texts:[42]},
  {n:170, pres:'intercipio',      perf:'intercepi',        sup:'interceptum',     inf:'intercipĕre',         meaning:'αρπάζω',                     texts:[45]},
  {n:171, pres:'interest',        perf:'interfuit',        sup:'-',               inf:'interesse',           meaning:'με ενδιαφέρει',              texts:[29]},
  {n:172, pres:'interficio',      perf:'interfeci',        sup:'interfectum',     inf:'interficĕre',         meaning:'σκοτώνω',                    texts:[16,18,19,49]},
  {n:173, pres:'interimo',        perf:'interemi',         sup:'interemptum',     inf:'interimĕre',          meaning:'εξολοθρεύω',                 texts:[21,49]},
  {n:174, pres:'interrogo',       perf:'interrogavi',      sup:'interrogatum',    inf:'interrogāre',         meaning:'ρωτώ',                       texts:[23,25,40,47]},
  {n:175, pres:'intervenio',      perf:'interveni',        sup:'interventum',     inf:'intervenīre',         meaning:'παρεμβαίνω',                 texts:[47]},
  {n:176, pres:'intro',           perf:'intravi',          sup:'intratum',        inf:'intrāre',             meaning:'μπαίνω',                     texts:[23]},
  {n:177, pres:'intromitto',      perf:'intromisi',        sup:'intromissum',     inf:'intromittĕre',        meaning:'βάζω μέσα',                  texts:[34]},
  {n:178, pres:'introrumpo',      perf:'introrupi',        sup:'introruptum',     inf:'introrumpĕre',        meaning:'εισβάλλω',                   texts:[48]},
  {n:179, pres:'intueor',         perf:'intuitus sum',     sup:'-',               inf:'intuēri',             meaning:'κοιτάζω',                    texts:[32]},
  {n:180, pres:'invado',          perf:'invasi',           sup:'invasum',         inf:'invadĕre',            meaning:'εισχωρώ',                    texts:[37]},
  {n:181, pres:'invenio',         perf:'inveni',           sup:'inventum',        inf:'invenīre',            meaning:'βρίσκω',                     texts:[48]},
  {n:182, pres:'investigo',       perf:'investigavi',      sup:'investigatum',    inf:'investigāre',         meaning:'αναζητώ',                    texts:[28]},
  {n:183, pres:'iubeo',           perf:'iussi',            sup:'iussum',          inf:'iubēre',              meaning:'διατάζω',                    texts:[16,34,48]},
  {n:184, pres:'iudico',          perf:'iudicavi',         sup:'iudicatum',       inf:'iudicāre',            meaning:'κρίνω',                      texts:[40,50]},
  // ── L ──
  {n:185, pres:'lacesso',         perf:'lacessivi',        sup:'lacessitum',      inf:'lacessĕre',           meaning:'προκαλώ',                    texts:[31]},
  {n:186, pres:'lateo',           perf:'latui',            sup:'-',               inf:'latēre',              meaning:'κρύβομαι',                   texts:[20]},
  {n:187, pres:'laudo',           perf:'laudavi',          sup:'laudatum',        inf:'laudāre',             meaning:'επαινώ',                     texts:[30,46]},
  {n:188, pres:'lectito',         perf:'lectitavi',        sup:'lectitatum',      inf:'lectitāre',           meaning:'διαβάζω συχνά',              texts:[26]},
  {n:189, pres:'lego',            perf:'legi',             sup:'lectum',          inf:'legĕre',              meaning:'διαβάζω / μαζεύω',           texts:[27,47]},
  {n:190, pres:'licet',           perf:'licuit',           sup:'-',               inf:'licēre',              meaning:'επιτρέπεται',                texts:[39]},
  {n:191, pres:'loquor',          perf:'locutus sum',      sup:'-',               inf:'loqui',               meaning:'μιλώ',                       texts:[41]},
  {n:192, pres:'ludo',            perf:'lusi',             sup:'lusum',           inf:'ludĕre',              meaning:'παίζω',                      texts:[26]},
  // ── M ──
  {n:193, pres:'malo',            perf:'malui',            sup:'-',               inf:'malle',               meaning:'προτιμώ',                    texts:[36,47]},
  {n:194, pres:'maneo',           perf:'mansi',            sup:'mansum',          inf:'manēre',              meaning:'περιμένω',                   texts:[43]},
  {n:195, pres:'medeor',          perf:'-',                sup:'-',               inf:'medēri',              meaning:'γιατρεύω',                   texts:[33]},
  {n:196, pres:'memini',          perf:'-',                sup:'-',               inf:'meminisse',           meaning:'θυμάμαι',                    texts:[25,36,40]},
  {n:197, pres:'mentior',         perf:'mentitus sum',     sup:'-',               inf:'mentiri',             meaning:'λέω ψέματα',                 texts:[24]},
  {n:198, pres:'mereo',           perf:'merui',            sup:'meritum',         inf:'merēre',              meaning:'αξίζω / υπηρετώ',            texts:[30]},
  {n:199, pres:'metuo',           perf:'metui',            sup:'metutum',         inf:'metuĕre',             meaning:'φοβάμαι',                    texts:[44]},
  {n:200, pres:'minitor',         perf:'minitatus sum',    sup:'-',               inf:'minitāri',            meaning:'απειλώ',                     texts:[40]},
  {n:201, pres:'miror',           perf:'miratus sum',      sup:'-',               inf:'mirari',              meaning:'θαυμάζω',                    texts:[36]},
  {n:202, pres:'miseror',         perf:'miseratus sum',    sup:'-',               inf:'miserari',            meaning:'θρηνώ, λυπάμαι',             texts:[17,20,35]},
  {n:203, pres:'mitto',           perf:'misi',             sup:'missum',          inf:'mittĕre',             meaning:'στέλνω / ρίχνω',             texts:[16,28,36,45,50]},
  {n:204, pres:'molior',          perf:'molitus sum',      sup:'-',               inf:'molīri',              meaning:'μηχανεύομαι',                texts:[49]},
  {n:205, pres:'moneo',           perf:'monui',            sup:'monitum',         inf:'monēre',              meaning:'συμβουλεύω',                 texts:[45,48]},
  {n:206, pres:'morior',          perf:'mortuus sum',      sup:'-',               inf:'mori',                meaning:'πεθαίνω',                    texts:[20,23,26,38,39,43]},
  {n:207, pres:'moveo',           perf:'movi',             sup:'motum',           inf:'movēre',              meaning:'κινώ',                       texts:[23]},
  {n:208, pres:'multo',           perf:'multavi',          sup:'multatum',        inf:'multāre',             meaning:'τιμωρώ',                     texts:[31]},
  // ── N ──
  {n:209, pres:'narro',           perf:'narravi',          sup:'narratum',        inf:'narrāre',             meaning:'αφηγούμαι',                  texts:[36]},
  {n:210, pres:'nascor',          perf:'natus sum',        sup:'-',               inf:'nasci',               meaning:'γεννιέμαι',                  texts:[27,31,42]},
  {n:211, pres:'neglego',         perf:'neglexi',          sup:'neglectum',       inf:'neglegĕre',           meaning:'αδιαφορώ',                   texts:[22]},
  {n:212, pres:'nequeo',          perf:'nequi(v)i',        sup:'-',               inf:'nequīre',             meaning:'δεν μπορώ',                  texts:[37]},
  {n:213, pres:'nescio',          perf:'nesci(v)i',        sup:'nescitum',        inf:'nescīre',             meaning:'αγνοώ, δεν ξέρω',            texts:[44]},
  {n:214, pres:'nolo',            perf:'nolui',            sup:'-',               inf:'nolle',               meaning:'δεν θέλω',                   texts:[25,28,40,47]},
  {n:215, pres:'nosco',           perf:'novi',             sup:'notum',           inf:'noscĕre',             meaning:'γνωρίζω',                    texts:[28]},
  {n:216, pres:'nuntio',          perf:'nuntiavi',         sup:'nuntiatum',       inf:'nuntiāre',            meaning:'αναγγέλλω',                  texts:[34,48]},
  // ── O ──
  {n:217, pres:'obfero',          perf:'obtuli',           sup:'oblatum',         inf:'obferre',             meaning:'φέρνω',                      texts:[39]},
  {n:218, pres:'obicio',          perf:'obieci',           sup:'obiectum',        inf:'obicĕre',             meaning:'ρίχνω, μέμφομαι',            texts:[30,32,47]},
  {n:219, pres:'obiurgo',         perf:'obiurgavi',        sup:'obiurgatum',      inf:'obiurgāre',           meaning:'μαλώνω',                     texts:[49]},
  {n:220, pres:'obsequor',        perf:'obsecutus sum',    sup:'-',               inf:'obsequi',             meaning:'κάνω το χατίρι',             texts:[37]},
  {n:221, pres:'obsigno',         perf:'obsignavi',        sup:'obsignatum',      inf:'obsignāre',           meaning:'υπογράφω',                   texts:[17]},
  {n:222, pres:'obsolesco',       perf:'obsolevi',         sup:'obsoletum',       inf:'obsolescĕre',         meaning:'είμαι παλιός',               texts:[41]},
  {n:223, pres:'obtineo',         perf:'obtinui',          sup:'obtentum',        inf:'obtinēre',            meaning:'πετυχαίνω',                  texts:[50]},
  {n:224, pres:'occido',          perf:'occidi',           sup:'occisum',         inf:'occidĕre',            meaning:'σκοτώνω',                    texts:[16,19,23]},
  {n:225, pres:'occupo',          perf:'occupavi',         sup:'occupatum',       inf:'occupāre',            meaning:'καταλαμβάνω',                texts:[17,40]},
  {n:226, pres:'occurro',         perf:'occu(cu)rri',      sup:'occursum',        inf:'occurrĕre',           meaning:'επιτίθεμαι',                 texts:[16,29]},
  {n:227, pres:'opprimo',         perf:'oppressi',         sup:'oppressum',       inf:'opprimĕre',           meaning:'πιάνω επ\' αυτοφώρω',         texts:[47]},
  {n:228, pres:'oppugno',         perf:'oppugnavi',        sup:'oppugnatum',      inf:'oppugnāre',           meaning:'πολιορκώ',                   texts:[43]},
  {n:229, pres:'orior',           perf:'ortus sum',        sup:'-',               inf:'orīri',               meaning:'ανατέλλω / γεννιέμαι',       texts:[48]},
  {n:230, pres:'oro',             perf:'oravi',            sup:'oratum',          inf:'orāre',               meaning:'παρακαλώ',                   texts:[23]},
  {n:231, pres:'osculor',         perf:'osculatus sum',    sup:'-',               inf:'osculari',            meaning:'φιλώ',                       texts:[34]},
  {n:232, pres:'ostendo',         perf:'ostendi',          sup:'ostentum',        inf:'ostendĕre',           meaning:'δείχνω',                     texts:[25,40]},
  // ── P ──
  {n:233, pres:'paenitet',        perf:'paenituit',        sup:'-',               inf:'paenitēre',           meaning:'μετανιώνω',                  texts:[27]},
  {n:234, pres:'pareo',           perf:'parui',            sup:'paritum',         inf:'parēre',              meaning:'υπακούω',                    texts:[22,46]},
  {n:235, pres:'pario',           perf:'peperi',           sup:'partum',          inf:'parĕre',              meaning:'γεννώ / κερδίζω',            texts:[37,43]},
  {n:236, pres:'paro',            perf:'paravi',           sup:'paratum',         inf:'parāre',              meaning:'ετοιμάζω',                   texts:[23]},
  {n:237, pres:'patior',          perf:'passus sum',       sup:'-',               inf:'pati',                meaning:'ανέχομαι, υπομένω',          texts:[43]},
  {n:238, pres:'penso',           perf:'pensavi',          sup:'pensatum',        inf:'pensāre',             meaning:'ζυγίζω',                     texts:[21]},
  {n:239, pres:'percello',        perf:'perculi',          sup:'perculsum',       inf:'percellĕre',          meaning:'ανατρέπω',                   texts:[33]},
  {n:240, pres:'perdo',           perf:'perdidi',          sup:'perditum',        inf:'perdĕre',             meaning:'χάνω',                       texts:[29,33]},
  {n:241, pres:'pereo',           perf:'perii',            sup:'peritum',         inf:'perīre',              meaning:'χάνομαι, πεθαίνω',           texts:[48]},
  {n:242, pres:'pergo',           perf:'perrexi',          sup:'perrectum',       inf:'pergĕre',             meaning:'κατευθύνομαι',               texts:[18,43]},
  {n:243, pres:'perlego',         perf:'perlegi',          sup:'perlectum',       inf:'perlegĕre',           meaning:'διαβάζω ως το τέλος',        texts:[45]},
  {n:244, pres:'permoveo',        perf:'permovi',          sup:'permotum',        inf:'permovēre',           meaning:'παρακινώ',                   texts:[31]},
  {n:245, pres:'persedeo',        perf:'persedi',          sup:'persessum',       inf:'persedēre',           meaning:'κάθομαι για ώρα',            texts:[38]},
  {n:246, pres:'persuadeo',       perf:'persuasi',         sup:'persuasum',       inf:'persuadēre',          meaning:'πείθω',                      texts:[45,48]},
  {n:247, pres:'pertineo',        perf:'pertinui',         sup:'pertentum',       inf:'pertinēre',           meaning:'αφορώ',                      texts:[37]},
  {n:248, pres:'perturbo',        perf:'perturbavi',       sup:'perturbatum',     inf:'perturbāre',          meaning:'ταράζω',                     texts:[17]},
  {n:249, pres:'pervenio',        perf:'perveni',          sup:'perventum',       inf:'pervenīre',           meaning:'φθάνω',                      texts:[42,43]},
  {n:250, pres:'peto',            perf:'peti(v)i',         sup:'petitum',         inf:'petĕre',              meaning:'ορμώ / ζητώ',                texts:[31,38]},
  {n:251, pres:'placeo',          perf:'placui',           sup:'placitum',        inf:'placēre',             meaning:'αρέσω / αποφασίζω',          texts:[35,41,50]},
  {n:252, pres:'pono',            perf:'posui',            sup:'positum',         inf:'ponĕre',              meaning:'τοποθετώ',                   texts:[34]},
  {n:253, pres:'populor',         perf:'populatus sum',    sup:'-',               inf:'populari',            meaning:'λεηλατώ',                    texts:[43]},
  {n:254, pres:'posco',           perf:'poposci',          sup:'postulatum',      inf:'poscĕre',             meaning:'ζητώ',                       texts:[49]},
  {n:255, pres:'possum',          perf:'potui',            sup:'-',               inf:'posse',               meaning:'μπορώ',                      texts:[17,28,32,33,36,39,43,44,45]},
  {n:256, pres:'praebeo',         perf:'praebui',          sup:'praebitum',       inf:'praebēre',            meaning:'παρέχω',                     texts:[36]},
  {n:257, pres:'praecipio',       perf:'praecepi',         sup:'praeceptum',      inf:'praecipĕre',          meaning:'καθοδηγώ',                   texts:[48]},
  {n:258, pres:'praedico',        perf:'praedicavi',       sup:'praedicatum',     inf:'praedicāre',          meaning:'διακηρύσσω',                 texts:[17,48]},
  {n:259, pres:'praeripio',       perf:'praeripui',        sup:'praereptum',      inf:'praeripĕre',          meaning:'αρπάζω',                     texts:[49]},
  {n:260, pres:'praesum',         perf:'praefui',          sup:'-',               inf:'praeesse',            meaning:'προΐσταμαι',                 texts:[22,31]},
  {n:261, pres:'praetendo',       perf:'praetendi',        sup:'praetentum',      inf:'praetendĕre',         meaning:'τεντώνω μπροστά',            texts:[20]},
  {n:262, pres:'praeterequito',   perf:'praeterequitavi',  sup:'praeterequitatum',inf:'praeterequitāre',     meaning:'περνώ έφιππος',              texts:[31]},
  {n:263, pres:'premo',           perf:'pressi',           sup:'pressum',         inf:'premĕre',             meaning:'πιέζω',                      texts:[39]},
  {n:264, pres:'produco',         perf:'produxi',          sup:'productum',       inf:'producĕre',           meaning:'οδηγώ μπροστά',              texts:[16]},
  {n:265, pres:'prohibeo',        perf:'prohibui',         sup:'prohibitum',      inf:'prohibēre',           meaning:'εμποδίζω',                   texts:[18,33,39]},
  {n:266, pres:'proicio',         perf:'proieci',          sup:'proiectum',       inf:'proicĕre',            meaning:'ρίχνω, πετάω',               texts:[16]},
  {n:267, pres:'propago',         perf:'propagavi',        sup:'propagatum',      inf:'propagāre',           meaning:'αφήνω απογόνους',            texts:[33]},
  {n:268, pres:'propono',         perf:'proposui',         sup:'propositum',      inf:'proponĕre',           meaning:'βάζω μπροστά μου',           texts:[32]},
  {n:269, pres:'prorepo',         perf:'prorepsi',         sup:'proreptum',       inf:'prorepĕre',           meaning:'σέρνομαι',                   texts:[20]},
  {n:270, pres:'prorumpo',        perf:'prorupi',          sup:'proruptum',       inf:'prorumpĕre',          meaning:'ξεσπώ',                      texts:[23]},
  {n:271, pres:'prosterno',       perf:'prostravi',        sup:'prostratum',      inf:'prosternĕre',         meaning:'ρίχνω κάτω',                 texts:[33]},
  {n:272, pres:'provideo',        perf:'providi',          sup:'provisum',        inf:'providēre',           meaning:'προνοώ',                     texts:[45]},
  {n:273, pres:'pugno',           perf:'pugnavi',          sup:'pugnatum',        inf:'pugnāre',             meaning:'μάχομαι',                    texts:[31,37]},
  {n:274, pres:'puto',            perf:'putavi',           sup:'putatum',         inf:'putāre',              meaning:'νομίζω, θεωρώ',              texts:[22,25,39,44,46]},
  // ── Q ──
  {n:275, pres:'quaero',          perf:'quaesi(v)i',       sup:'quaesitum',       inf:'quaerĕre',            meaning:'ζητώ, ρωτώ',                 texts:[24]},
  {n:276, pres:'quaeso',          perf:'-',                sup:'-',               inf:'quaesĕre',            meaning:'παρακαλώ',                   texts:[28]},
  {n:277, pres:'quasso',          perf:'quassavi',         sup:'quassatum',       inf:'quassāre',            meaning:'συντρίβω',                   texts:[33]},
  {n:278, pres:'queror',          perf:'questus sum',      sup:'-',               inf:'queri',               meaning:'παραπονιέμαι',               texts:[17]},
  {n:279, pres:'quiesco',         perf:'quievi',           sup:'quietum',         inf:'quiescĕre',           meaning:'ησυχάζω',                    texts:[23]},
  // ── R ──
  {n:280, pres:'recedo',          perf:'recessi',          sup:'recessum',        inf:'recedĕre',            meaning:'αποσύρομαι',                 texts:[20,27]},
  {n:281, pres:'recipio',         perf:'recepi',           sup:'receptum',        inf:'recipĕre',            meaning:'παίρνω πίσω',                texts:[21]},
  {n:282, pres:'reddo',           perf:'reddidi',          sup:'redditum',        inf:'reddĕre',             meaning:'καθιστώ, κάνω',              texts:[37]},
  {n:283, pres:'redeo',           perf:'redi(v)i',         sup:'reditum',         inf:'redīre',              meaning:'επιστρέφω',                  texts:[21,23,28,29]},
  {n:284, pres:'refero',          perf:'re(t)tuli',        sup:'relatum',         inf:'referre',             meaning:'παραδίδω / αναφέρω',         texts:[16,34,44]},
  {n:285, pres:'reficio',         perf:'refeci',           sup:'refectum',        inf:'reficĕre',            meaning:'ξεκουράζω',                  texts:[18]},
  {n:286, pres:'rego',            perf:'rexi',             sup:'rectum',          inf:'regĕre',              meaning:'κυβερνώ',                    texts:[46]},
  {n:287, pres:'relinquo',        perf:'reliqui',          sup:'relictum',        inf:'relinquĕre',          meaning:'αφήνω',                      texts:[32,35]},
  {n:288, pres:'remaneo',         perf:'remansi',          sup:'remansum',        inf:'remanēre',            meaning:'παραμένω',                   texts:[17]},
  {n:289, pres:'repono',          perf:'reposui',          sup:'repositum',       inf:'reponĕre',            meaning:'τοποθετώ',                   texts:[22]},
  {n:290, pres:'reseco',          perf:'resecui',          sup:'resectum',        inf:'resecāre',            meaning:'κόβω',                       texts:[49]},
  {n:291, pres:'resero',          perf:'reseravi',         sup:'reseratum',       inf:'reserāre',            meaning:'ανοίγω',                     texts:[34]},
  {n:292, pres:'respondeo',       perf:'respondi',         sup:'responsum',       inf:'respondēre',          meaning:'απαντώ',                     texts:[23,24,29,47]},
  {n:293, pres:'revertor',        perf:'reversus sum',     sup:'-',               inf:'reverti',             meaning:'επιστρέφω',                  texts:[21,31,34,48]},
  {n:294, pres:'revoco',          perf:'revocavi',         sup:'revocatum',       inf:'revocāre',            meaning:'ανακαλώ',                    texts:[33]},
  {n:295, pres:'rideo',           perf:'risi',             sup:'risum',           inf:'ridēre',              meaning:'γελώ',                       texts:[29]},
  {n:296, pres:'rogo',            perf:'rogavi',           sup:'rogatum',         inf:'rogāre',              meaning:'παρακαλώ / ρωτώ',            texts:[21,38]},
  {n:297, pres:'ruo',             perf:'rui',              sup:'rutum',           inf:'ruĕre',               meaning:'ορμώ',                       texts:[31]},
  // ── S ──
  {n:298, pres:'saluto',          perf:'salutavi',         sup:'salutatum',       inf:'salutāre',            meaning:'χαιρετίζω',                  texts:[20,34]},
  {n:299, pres:'sano',            perf:'sanavi',           sup:'sanatum',         inf:'sanāre',              meaning:'θεραπεύω',                   texts:[33]},
  {n:300, pres:'sapio',           perf:'sapi(v)i',         sup:'-',               inf:'sapĕre',              meaning:'είμαι σοφός',                texts:[39,46]},
  {n:301, pres:'scio',            perf:'sci(v)i',          sup:'scitum',          inf:'scīre',               meaning:'γνωρίζω',                    texts:[24,25,39,41]},
  {n:302, pres:'scribo',          perf:'scripsi',          sup:'scriptum',        inf:'scribĕre',            meaning:'γράφω',                      texts:[26,27,35,41,45]},
  {n:303, pres:'sentio',          perf:'sensi',            sup:'sensum',          inf:'sentīre',             meaning:'καταλαβαίνω',                texts:[18,24,33,37]},
  {n:304, pres:'sequor',          perf:'secutus sum',      sup:'-',               inf:'sequi',               meaning:'ακολουθώ',                   texts:[21,23,42]},
  {n:305, pres:'servio',          perf:'servivi',          sup:'servitum',        inf:'servīre',             meaning:'υπηρετώ',                    texts:[22]},
  {n:306, pres:'simulo',          perf:'simulavi',         sup:'simulatum',       inf:'simulāre',            meaning:'προσποιούμαι',               texts:[23]},
  {n:307, pres:'soleo',           perf:'solitus sum',      sup:'-',               inf:'solēre',              meaning:'συνηθίζω',                   texts:[29,34,47]},
  {n:308, pres:'solvo',           perf:'solvi',            sup:'solutum',         inf:'solvĕre',             meaning:'λύνω',                       texts:[36]},
  {n:309, pres:'specto',          perf:'spectavi',         sup:'spectatum',       inf:'spectāre',            meaning:'κοιτάζω',                    texts:[28,36]},
  {n:310, pres:'spero',           perf:'speravi',          sup:'speratum',        inf:'sperāre',             meaning:'ελπίζω',                     texts:[22,27,45]},
  {n:311, pres:'spolio',          perf:'spoliavi',         sup:'spoliatum',       inf:'spoliāre',            meaning:'απογυμνώνω',                 texts:[31]},
  {n:312, pres:'stabilio',        perf:'stabilivi',        sup:'stabilitum',      inf:'stabilīre',           meaning:'στεριώνω',                   texts:[22]},
  {n:313, pres:'sto',             perf:'steti',            sup:'statum',          inf:'stāre',               meaning:'στέκομαι',                   texts:[38]},
  {n:314, pres:'strangulo',       perf:'strangulavi',      sup:'strangulatum',    inf:'strangulāre',         meaning:'στραγγαλίζω',                texts:[19]},
  {n:315, pres:'subvenio',        perf:'subveni',          sup:'subventum',       inf:'subvenīre',           meaning:'βοηθώ',                      texts:[33,37]},
  {n:316, pres:'succurrit',       perf:'succurrit',        sup:'succursum',       inf:'succurrĕre',          meaning:'έρχεται στο μυαλό',          texts:[43]},
  {n:317, pres:'sum',             perf:'fui',              sup:'-',               inf:'esse',                meaning:'είμαι',                      texts:[16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50]},
  {n:318, pres:'sumo',            perf:'sumpsi',           sup:'sumptum',         inf:'sumĕre',              meaning:'παίρνω',                     texts:[23,25]},
  {n:319, pres:'suscipio',        perf:'suscepi',          sup:'susceptum',       inf:'suscipĕre',           meaning:'παραλαμβάνω',                texts:[30,44]},
  // ── T ──
  {n:320, pres:'taceo',           perf:'tacui',            sup:'tacitum',         inf:'tacēre',              meaning:'σωπαίνω',                    texts:[41,48]},
  {n:321, pres:'teneo',           perf:'tenui',            sup:'tentum',          inf:'tenēre',              meaning:'κρατώ',                      texts:[17,29]},
  {n:322, pres:'timeo',           perf:'timui',            sup:'-',               inf:'timēre',              meaning:'φοβάμαι',                    texts:[47]},
  {n:323, pres:'trado',           perf:'tradidi',          sup:'traditum',        inf:'tradĕre',             meaning:'παραδίδω',                   texts:[16,19,28,35]},
  {n:324, pres:'traho',           perf:'traxi',            sup:'tractum',         inf:'trahĕre',             meaning:'τραβώ',                      texts:[18,23,43]},
  {n:325, pres:'transfigo',       perf:'transfixi',        sup:'transfixum',      inf:'transfigĕre',         meaning:'διαπερνώ',                   texts:[31]},
  {n:326, pres:'tutor',           perf:'tutatus sum',      sup:'tutatum',         inf:'tutāri',              meaning:'προστατεύω',                 texts:[25]},
  // ── U ──
  {n:327, pres:'utor',            perf:'usus sum',         sup:'-',               inf:'uti',                 meaning:'χρησιμοποιώ',                texts:[36,39,41]},
  // ── V ──
  {n:328, pres:'veneror',         perf:'veneratus sum',    sup:'-',               inf:'venerari',            meaning:'προσκυνώ',                   texts:[34]},
  {n:329, pres:'venio',           perf:'veni',             sup:'ventum',          inf:'venīre',              meaning:'έρχομαι',                    texts:[24,27,29,34,36,37,43,49]},
  {n:330, pres:'vereor',          perf:'veritus sum',      sup:'-',               inf:'verēri',              meaning:'φοβάμαι',                    texts:[45]},
  {n:331, pres:'verto',           perf:'verti',            sup:'versum',          inf:'vertĕre',             meaning:'στρέφω',                     texts:[16]},
  {n:332, pres:'video',           perf:'vidi',             sup:'visum',           inf:'vidēre',              meaning:'βλέπω',                      texts:[18,26,27,30,42,43,47,48]},
  {n:333, pres:'vincio',          perf:'vinxi',            sup:'vinctum',         inf:'vincīre',             meaning:'δένω',                       texts:[33]},
  {n:334, pres:'vinco',           perf:'vici',             sup:'victum',          inf:'vincĕre',             meaning:'νικώ',                       texts:[19,23,36]},
  {n:335, pres:'vitupero',        perf:'vituperavi',       sup:'vituperatum',     inf:'vituperāre',          meaning:'επικρίνω',                   texts:[46]},
  {n:336, pres:'vivo',            perf:'vixi',             sup:'victum',          inf:'vivĕre',              meaning:'ζω',                         texts:[23,30,35,38,41]},
  {n:337, pres:'voco',            perf:'vocavi',           sup:'vocatum',         inf:'vocāre',              meaning:'καλώ',                       texts:[49]},
  {n:338, pres:'volo',            perf:'volui',            sup:'-',               inf:'velle',               meaning:'θέλω',                       texts:[22,24,37,41,47,49]},
  {n:339, pres:'vulnero',         perf:'vulneravi',        sup:'vulneratum',      inf:'vulnerāre',           meaning:'τραυματίζω',                 texts:[19,49]},
];

// Build a map: text number → array of verb entries
const LAT_KATA_BY_TEXT = {};
for (let t = 16; t <= 50; t++) LAT_KATA_BY_TEXT[t] = [];
LAT_KATA_DB.forEach(v => {
  v.texts.forEach(t => { if (LAT_KATA_BY_TEXT[t]) LAT_KATA_BY_TEXT[t].push(v); });
});
