// ============================================================
//  ΣΥΝΗΡΗΜΕΝΑ ΡΗΜΑΤΑ — Game Controller
//  Depends on: synirimmena/data.js, shared-engine.js
// ============================================================

const SYN_PREFIX = 'syn';
let _synFilter = null;

function _synSetMode(mode){
  gramSetMode(SYN_PREFIX,mode);
  document.querySelectorAll('#syn-wrap .lmode-btn').forEach(b=>b.classList.remove('selected'));
  document.getElementById(`syn-mode-${mode}`)?.classList.add('selected');
}

function openSynirimmena(levelId, mode){
  document.getElementById('syn-overlay').classList.add('active');
  document.body.style.overflow='hidden';
  if(!document.getElementById('syn-screen-levels')) _synBuild();
  // Auto-navigate to a specific level+mode when QR-scanned
  if (levelId) {
    setTimeout(() => {
      const card = document.querySelector(`#syn-level-grid .lvl-card[data-lvl-id="${levelId}"]`);
      if (card) card.click();
      if (mode) setTimeout(() => gramSetMode('syn', mode), 60);
    }, 60);
  }
}
function closeSynirimmena(){
  (_gramCleanup['syn']||function(){})();
  document.getElementById('syn-overlay').classList.remove('active');
  document.body.style.overflow='';
  const wrap=document.getElementById('syn-wrap');
  if(wrap){wrap.querySelectorAll('.lyo-screen').forEach(s=>s.classList.remove('active'));document.getElementById('syn-screen-levels')?.classList.add('active');}
}

// ── Build HTML ──
function _synBuild(){
  const wrap=document.getElementById('syn-wrap');
  wrap.innerHTML=gramBuildScreens(SYN_PREFIX,'Συνηρημένα Ρήματα','τιμῶ · ποιῶ · δηλῶ — Αρχαία Ελληνική Γραμματική');

  // Match screen is now generated by gramBuildScreens.
  // Override exit button so synirimmena's custom match uses _synMatchExit (not gramMatchExit).
  const matchExitBtn=document.querySelector('#syn-screen-match .lbtn-secondary');
  if(matchExitBtn) matchExitBtn.onclick=_synMatchExit;

  // Wire style fix for selects inside this overlay
  wrap.querySelectorAll('select').forEach(s=>{
    s.style.cssText='width:100%;padding:9px 12px;background:#241e16;border:1px solid #3d3020;border-radius:8px;color:#e8dcc8;font-size:0.93rem;cursor:pointer;font-family:inherit;';
  });

  // Build level grid
  gramBuildLevelGrid(SYN_PREFIX,SYN_LEVELS,lvl=>{
    _synFilter=lvl.filter;
    document.getElementById('syn-sett-title').textContent=`Επίπεδο ${lvl.id} — ${lvl.desc}`;
    document.getElementById('syn-sett-back').onclick=()=>{
      document.querySelectorAll('#syn-wrap .lyo-screen').forEach(s=>s.classList.remove('active'));
      document.getElementById('syn-screen-levels').classList.add('active');
    };
    document.querySelectorAll('#syn-wrap .lyo-screen').forEach(s=>s.classList.remove('active'));
    document.getElementById('syn-screen-settings').classList.add('active');
  });

  // Wire launch button
  document.getElementById('syn-launch-btn').onclick=_synLaunch;

  // Build polytonic keyboard
  gramBuildKeyboard(SYN_PREFIX);
}

// ── Launch ──
function _synLaunch(){
  const mode=gramGetMode(SYN_PREFIX);
  const timer=parseInt(document.getElementById('syn-sel-time').value);
  const lives=parseInt(document.getElementById('syn-sel-lives').value);

  if(mode==='match'){
    _synStartMatch(_synFilter);
    return;
  }

  gramRunGame({
    prefix:SYN_PREFIX,
    G:SYN_G,
    keysFn:synKeys,
    stemFn:synStem,
    qtFn:synQText,
    filter:_synFilter,
    mode,lives,timer,
    wrapId:'syn-wrap',
  });
}

// ══════════════════════════════════════
// ΑΝΤΙΣΤΟΙΧΙΣΗ (Matching Mode)
// ══════════════════════════════════════

let _synMatchState={
  pairs:[],          // [{key, uncontracted, contracted, id}]
  batchStart:0,
  batchSize:6,
  matched:new Set(), // ids of matched pairs
  selectedLeft:null, // id of selected left card
  scoreMatched:0,
  total:0,
};

function _synStartMatch(filter){
  const keys=synKeys(filter);
  if(!keys.length){alert('Δεν βρέθηκαν ζεύγη για αντιστοίχιση.');return;}

  // Build unique pairs (deduplicate by contracted form within a single batch)
  const allPairs=[];
  const seenContracted=new Set();
  for(const k of keys){
    const g=SYN_G[k];
    const c=g.endings[0];
    if(!seenContracted.has(c)){
      seenContracted.add(c);
      allPairs.push({id:k, uncontracted:g.uncontracted||'—', contracted:c, key:k});
    }
  }

  // Shuffle
  for(let i=allPairs.length-1;i>0;i--){
    const j=Math.floor(Math.random()*(i+1));
    [allPairs[i],allPairs[j]]=[allPairs[j],allPairs[i]];
  }

  _synMatchState={
    pairs:allPairs,
    batchStart:0,
    batchSize:6,
    matched:new Set(),
    selectedLeft:null,
    scoreMatched:0,
    total:allPairs.length,
  };

  document.querySelectorAll('#syn-wrap .lyo-screen').forEach(s=>s.classList.remove('active'));
  document.getElementById('syn-screen-match').classList.add('active');
  const lblEl=document.getElementById('syn-match-lbl');
  if(lblEl)lblEl.textContent='Αντίστοιχισε ασυναίρετο → συνηρημένο';
  _synRenderMatchBatch();
}

function _synRenderMatchBatch(){
  const st=_synMatchState;
  const batch=st.pairs.slice(st.batchStart, st.batchStart+st.batchSize);

  // Update score display
  const scoreEl=document.getElementById('syn-match-score');
  if(scoreEl)scoreEl.textContent=`${st.scoreMatched}/${st.total}`;

  // Shuffle right column
  const rightItems=[...batch];
  for(let i=rightItems.length-1;i>0;i--){
    const j=Math.floor(Math.random()*(i+1));
    [rightItems[i],rightItems[j]]=[rightItems[j],rightItems[i]];
  }

  const body=document.getElementById('syn-match-body');
  if(!body)return;
  body.innerHTML=`
<div class="syn-match-cols">
  <div class="syn-match-col syn-match-left" id="syn-left-col"></div>
  <div class="syn-match-col syn-match-right" id="syn-right-col"></div>
</div>`;

  const leftCol=document.getElementById('syn-left-col');
  const rightCol=document.getElementById('syn-right-col');

  batch.forEach(p=>{
    const d=document.createElement('div');
    d.className='syn-match-card syn-left-card';
    d.dataset.id=p.id;
    d.textContent=p.uncontracted;
    d.onclick=()=>_synMatchClickLeft(p.id);
    leftCol.appendChild(d);
  });

  rightItems.forEach(p=>{
    const d=document.createElement('div');
    d.className='syn-match-card syn-right-card';
    d.dataset.id=p.id;
    d.textContent=p.contracted;
    d.onclick=()=>_synMatchClickRight(p.id);
    rightCol.appendChild(d);
  });

  const fb=document.getElementById('syn-match-fb');
  if(fb){fb.textContent='';fb.className='lfeedback';}
}

function _synCardByDataId(col, id){
  return [...document.querySelectorAll(`#${col} .syn-match-card`)].find(el=>el.dataset.id===id)||null;
}

function _synMatchClickLeft(id){
  if(_synMatchState.matched.has(id))return;
  document.querySelectorAll('#syn-left-col .syn-match-card').forEach(c=>c.classList.remove('syn-selected'));
  const card=_synCardByDataId('syn-left-col',id);
  if(card)card.classList.add('syn-selected');
  _synMatchState.selectedLeft=id;
}

function _synMatchClickRight(id){
  const st=_synMatchState;
  if(st.matched.has(id))return;
  if(!st.selectedLeft)return;

  const leftId=st.selectedLeft;
  const ok=(leftId===id);

  const leftCard=_synCardByDataId('syn-left-col',leftId);
  const rightCard=_synCardByDataId('syn-right-col',id);

  const fb=document.getElementById('syn-match-fb');

  if(ok){
    if(leftCard){leftCard.classList.remove('syn-selected');leftCard.classList.add('syn-matched');}
    if(rightCard)rightCard.classList.add('syn-matched');
    st.matched.add(id);
    st.scoreMatched++;
    st.selectedLeft=null;

    const scoreEl=document.getElementById('syn-match-score');
    if(scoreEl)scoreEl.textContent=`${st.scoreMatched}/${st.total}`;
    if(fb){fb.textContent='✓ Σωστό!';fb.className='lfeedback lok';}

    // Check if batch complete
    const batchIds=st.pairs.slice(st.batchStart,st.batchStart+st.batchSize).map(p=>p.id);
    if(batchIds.every(bid=>st.matched.has(bid))){
      const nextStart=st.batchStart+st.batchSize;
      if(nextStart>=st.pairs.length){
        _synMatchDone();
      }else{
        st.batchStart=nextStart;
        st.selectedLeft=null;
        setTimeout(()=>_synRenderMatchBatch(),700);
      }
    }
  }else{
    // Wrong match: flash red
    if(leftCard)leftCard.classList.add('syn-wrong');
    if(rightCard)rightCard.classList.add('syn-wrong');
    if(fb){
      const correct=st.pairs.find(p=>p.id===leftId);
      fb.textContent=`✗ Λάθος${correct?` — σωστό: ${correct.contracted}`:''}`;
      fb.className='lfeedback lerr';
    }
    setTimeout(()=>{
      if(leftCard)leftCard.classList.remove('syn-wrong');
      if(rightCard)rightCard.classList.remove('syn-wrong');
    },700);
  }
}

function _synMatchDone(){
  const body=document.getElementById('syn-match-body');
  if(body){
    body.innerHTML=`
<div style="text-align:center;padding:30px 0;">
  <div style="font-size:3rem;margin-bottom:12px;">🎉</div>
  <h2 style="font-family:'Cinzel',serif;color:#c9a44a;margin-bottom:8px;">Τέλεια!</h2>
  <p style="color:#8a7a60;">Αντιστοίχισες και τα ${_synMatchState.total} ζεύγη σωστά!</p>
  <div style="display:flex;gap:12px;justify-content:center;margin-top:24px;">
    <button class="lbtn lbtn-primary" style="width:auto;padding:11px 24px;" onclick="_synStartMatch(_synFilter)">Ξανά →</button>
    <button class="lbtn lbtn-secondary" onclick="_synShowLevels()">Επίπεδα</button>
  </div>
</div>`;
  }
  const fb=document.getElementById('syn-match-fb');
  if(fb){fb.textContent='';fb.className='lfeedback';}
}

function _synMatchExit(){
  document.querySelectorAll('#syn-wrap .lyo-screen').forEach(s=>s.classList.remove('active'));
  document.getElementById('syn-screen-levels').classList.add('active');
}

function _synShowLevels(){
  document.querySelectorAll('#syn-wrap .lyo-screen').forEach(s=>s.classList.remove('active'));
  document.getElementById('syn-screen-levels').classList.add('active');
}
